apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hound
  labels:
    app: hound
spec:
  replicas: 2
  # selector defaults from template labels
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: hound
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - name: hound
          image: k8scode/hound:v0.1.0
          livenessProbe:
            tcpSocket:
              port: 6379
            initialDelaySeconds: 900
            timeoutSeconds: 300
          ports:
            - containerPort: 8080
              protocol: TCP
