### ATTENTION ###
# k8s-staging-kubernetes is the staging container registry for ROOT level k8s.gcr.io images.
# Image promotion for this project is restricted to Release Managers.
#
# The following images are managed within this project:
# - cloud-controller-manager
# - conformance (will likely be moved to another staging project)
# - kube-apiserver
# - kube-controller-manager
# - kube-proxy
# - kube-scheduler
# - pause
#
# google group for gcr.io/k8s-staging-kubernetes is k8s-infra-staging-kubernetes@kubernetes.io

registries:
- name: gcr.io/k8s-staging-kubernetes
  src: true

# Promotes to the following GCR/AR locations:
# - *.gcr.io/k8s-artifacts-prod --> registry.k8s.io
# - *-docker.pkg.dev/k8s-artifacts-prod/images --> registry.k8s.io
- name: us.gcr.io/k8s-artifacts-prod
  service-account: k8s-infra-gcr-promoter@k8s-artifacts-prod.iam.gserviceaccount.com
- name: eu.gcr.io/k8s-artifacts-prod
  service-account: k8s-infra-gcr-promoter@k8s-artifacts-prod.iam.gserviceaccount.com
- name: asia.gcr.io/k8s-artifacts-prod
  service-account: k8s-infra-gcr-promoter@k8s-artifacts-prod.iam.gserviceaccount.com
- name: asia-east1-docker.pkg.dev/k8s-artifacts-prod/images
  service-account: k8s-infra-gcr-promoter@k8s-artifacts-prod.iam.gserviceaccount.com
- name: asia-south1-docker.pkg.dev/k8s-artifacts-prod/images
  service-account: k8s-infra-gcr-promoter@k8s-artifacts-prod.iam.gserviceaccount.com
- name: asia-northeast1-docker.pkg.dev/k8s-artifacts-prod/images
  service-account: k8s-infra-gcr-promoter@k8s-artifacts-prod.iam.gserviceaccount.com
- name: asia-northeast2-docker.pkg.dev/k8s-artifacts-prod/images
  service-account: k8s-infra-gcr-promoter@k8s-artifacts-prod.iam.gserviceaccount.com
- name: australia-southeast1-docker.pkg.dev/k8s-artifacts-prod/images
  service-account: k8s-infra-gcr-promoter@k8s-artifacts-prod.iam.gserviceaccount.com
- name: europe-north1-docker.pkg.dev/k8s-artifacts-prod/images
  service-account: k8s-infra-gcr-promoter@k8s-artifacts-prod.iam.gserviceaccount.com
- name: europe-southwest1-docker.pkg.dev/k8s-artifacts-prod/images
  service-account: k8s-infra-gcr-promoter@k8s-artifacts-prod.iam.gserviceaccount.com
- name: europe-west1-docker.pkg.dev/k8s-artifacts-prod/images
  service-account: k8s-infra-gcr-promoter@k8s-artifacts-prod.iam.gserviceaccount.com
- name: europe-west2-docker.pkg.dev/k8s-artifacts-prod/images
  service-account: k8s-infra-gcr-promoter@k8s-artifacts-prod.iam.gserviceaccount.com
- name: europe-west4-docker.pkg.dev/k8s-artifacts-prod/images
  service-account: k8s-infra-gcr-promoter@k8s-artifacts-prod.iam.gserviceaccount.com
- name: europe-west8-docker.pkg.dev/k8s-artifacts-prod/images
  service-account: k8s-infra-gcr-promoter@k8s-artifacts-prod.iam.gserviceaccount.com
- name: europe-west9-docker.pkg.dev/k8s-artifacts-prod/images
  service-account: k8s-infra-gcr-promoter@k8s-artifacts-prod.iam.gserviceaccount.com
- name: southamerica-west1-docker.pkg.dev/k8s-artifacts-prod/images
  service-account: k8s-infra-gcr-promoter@k8s-artifacts-prod.iam.gserviceaccount.com
- name: us-central1-docker.pkg.dev/k8s-artifacts-prod/images
  service-account: k8s-infra-gcr-promoter@k8s-artifacts-prod.iam.gserviceaccount.com
- name: us-east1-docker.pkg.dev/k8s-artifacts-prod/images
  service-account: k8s-infra-gcr-promoter@k8s-artifacts-prod.iam.gserviceaccount.com
- name: us-east4-docker.pkg.dev/k8s-artifacts-prod/images
  service-account: k8s-infra-gcr-promoter@k8s-artifacts-prod.iam.gserviceaccount.com
- name: us-east5-docker.pkg.dev/k8s-artifacts-prod/images
  service-account: k8s-infra-gcr-promoter@k8s-artifacts-prod.iam.gserviceaccount.com
- name: us-south1-docker.pkg.dev/k8s-artifacts-prod/images
  service-account: k8s-infra-gcr-promoter@k8s-artifacts-prod.iam.gserviceaccount.com
- name: us-west1-docker.pkg.dev/k8s-artifacts-prod/images
  service-account: k8s-infra-gcr-promoter@k8s-artifacts-prod.iam.gserviceaccount.com
- name: us-west2-docker.pkg.dev/k8s-artifacts-prod/images
  service-account: k8s-infra-gcr-promoter@k8s-artifacts-prod.iam.gserviceaccount.com

# Promotes to the following GCR/AR locations:
# - *.gcr.io/k8s-artifacts-prod/kubernetes --> registry.k8s.io/kubernetes
# - *-docker.pkg.dev/k8s-artifacts-prod/images/kubernetes --> registry.k8s.io/kubernetes
- name: us.gcr.io/k8s-artifacts-prod/kubernetes
  service-account: k8s-infra-gcr-promoter@k8s-artifacts-prod.iam.gserviceaccount.com
- name: eu.gcr.io/k8s-artifacts-prod/kubernetes
  service-account: k8s-infra-gcr-promoter@k8s-artifacts-prod.iam.gserviceaccount.com
- name: asia.gcr.io/k8s-artifacts-prod/kubernetes
  service-account: k8s-infra-gcr-promoter@k8s-artifacts-prod.iam.gserviceaccount.com
- name: asia-east1-docker.pkg.dev/k8s-artifacts-prod/images/kubernetes
  service-account: k8s-infra-gcr-promoter@k8s-artifacts-prod.iam.gserviceaccount.com
- name: asia-south1-docker.pkg.dev/k8s-artifacts-prod/images/kubernetes
  service-account: k8s-infra-gcr-promoter@k8s-artifacts-prod.iam.gserviceaccount.com
- name: asia-northeast1-docker.pkg.dev/k8s-artifacts-prod/images/kubernetes
  service-account: k8s-infra-gcr-promoter@k8s-artifacts-prod.iam.gserviceaccount.com
- name: asia-northeast2-docker.pkg.dev/k8s-artifacts-prod/images/kubernetes
  service-account: k8s-infra-gcr-promoter@k8s-artifacts-prod.iam.gserviceaccount.com
- name: australia-southeast1-docker.pkg.dev/k8s-artifacts-prod/images/kubernetes
  service-account: k8s-infra-gcr-promoter@k8s-artifacts-prod.iam.gserviceaccount.com
- name: europe-north1-docker.pkg.dev/k8s-artifacts-prod/images/kubernetes
  service-account: k8s-infra-gcr-promoter@k8s-artifacts-prod.iam.gserviceaccount.com
- name: europe-southwest1-docker.pkg.dev/k8s-artifacts-prod/images/kubernetes
  service-account: k8s-infra-gcr-promoter@k8s-artifacts-prod.iam.gserviceaccount.com
- name: europe-west1-docker.pkg.dev/k8s-artifacts-prod/images/kubernetes
  service-account: k8s-infra-gcr-promoter@k8s-artifacts-prod.iam.gserviceaccount.com
- name: europe-west2-docker.pkg.dev/k8s-artifacts-prod/images/kubernetes
  service-account: k8s-infra-gcr-promoter@k8s-artifacts-prod.iam.gserviceaccount.com
- name: europe-west4-docker.pkg.dev/k8s-artifacts-prod/images/kubernetes
  service-account: k8s-infra-gcr-promoter@k8s-artifacts-prod.iam.gserviceaccount.com
- name: europe-west8-docker.pkg.dev/k8s-artifacts-prod/images/kubernetes
  service-account: k8s-infra-gcr-promoter@k8s-artifacts-prod.iam.gserviceaccount.com
- name: europe-west9-docker.pkg.dev/k8s-artifacts-prod/images/kubernetes
  service-account: k8s-infra-gcr-promoter@k8s-artifacts-prod.iam.gserviceaccount.com
- name: southamerica-west1-docker.pkg.dev/k8s-artifacts-prod/images/kubernetes
  service-account: k8s-infra-gcr-promoter@k8s-artifacts-prod.iam.gserviceaccount.com
- name: us-central1-docker.pkg.dev/k8s-artifacts-prod/images/kubernetes
  service-account: k8s-infra-gcr-promoter@k8s-artifacts-prod.iam.gserviceaccount.com
- name: us-east1-docker.pkg.dev/k8s-artifacts-prod/images/kubernetes
  service-account: k8s-infra-gcr-promoter@k8s-artifacts-prod.iam.gserviceaccount.com
- name: us-east4-docker.pkg.dev/k8s-artifacts-prod/images/kubernetes
  service-account: k8s-infra-gcr-promoter@k8s-artifacts-prod.iam.gserviceaccount.com
- name: us-east5-docker.pkg.dev/k8s-artifacts-prod/images/kubernetes
  service-account: k8s-infra-gcr-promoter@k8s-artifacts-prod.iam.gserviceaccount.com
- name: us-south1-docker.pkg.dev/k8s-artifacts-prod/images/kubernetes
  service-account: k8s-infra-gcr-promoter@k8s-artifacts-prod.iam.gserviceaccount.com
- name: us-west1-docker.pkg.dev/k8s-artifacts-prod/images/kubernetes
  service-account: k8s-infra-gcr-promoter@k8s-artifacts-prod.iam.gserviceaccount.com
- name: us-west2-docker.pkg.dev/k8s-artifacts-prod/images/kubernetes
  service-account: k8s-infra-gcr-promoter@k8s-artifacts-prod.iam.gserviceaccount.com
