apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: azure-disk-premium-retain
provisioner: disk.csi.azure.com
parameters:
  skuName: PremiumV2_LRS
  cachingMode: None
  DiskIOPSReadWrite: "7000"
  DiskMBpsReadWrite: "250"
  fsType: ext4
reclaimPolicy: Retain
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
