apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mimir-credentials
  namespace: mimir
spec:
  data:
    - secretKey: .htpasswd
      remoteRef:
        key: mimir-credentials
        property: htpasswd
  secretStoreRef:
    kind: ClusterSecretStore
    name: k8s-infra-prow
