{
 "title": "Builds",
 "tags": [ "prow" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "org", "label": "Organisation", "query": "label_values(prow:job, org)" },
   {
    "name": "repo",
    "label": "Repository",
    "query": "label_values(prow:job{org=\"$org\"}, repo)"
   },
   {
    "name": "job",
    "query": "label_values(prow:job{org=\"$org\",repo=\"$repo\"}, name)"
   },
   {
    "name": "build",
    "query": "label_values(prow:job{org=\"$org\",repo=\"$repo\",name=\"$job\"}, id)"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Running / Pending Builds",
   "type": "graph",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count (prow:job{phase=\"Running\",org=\"$org\",repo=\"$repo\",name=\"$job\"})",
     "legendFormat": "running"
    },
    {
     "expr": "count (prow:job:pending{org=\"$org\",repo=\"$repo\",name=\"$job\"})",
     "legendFormat": "pending"
    }
   ]
  },
  {
   "title": "Pending Builds",
   "type": "table",
   "gridPos": { "h": 9, "w": 20, "x": 4, "y": 1 },
   "targets": [
    {
     "expr": "(time() - prow:job:pending_since_time{org=\"$org\",repo=\"$repo\",name=\"$job\"}) > 60"
    }
   ]
  },
  {
   "title": "Memory Requested",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 10 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 * (sum (prow:job:resource_requests_memory_bytes{org=\"$org\",repo=\"$repo\",name=\"$job\"}) / sum (prow:node:memory_capacity_bytes))",
     "legendFormat": "requests"
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 2, "y": 10 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 * (sum (prow:job:memory_working_set_bytes{phase=\"Running\",org=\"$org\",repo=\"$repo\",name=\"$job\"}) / sum (prow:node:memory_capacity_bytes))",
     "legendFormat": "used"
    }
   ]
  },
  {
   "title": "Memory Usage per Build",
   "type": "graph",
   "gridPos": { "h": 10, "w": 10, "x": 4, "y": 10 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (id) (prow:job:memory_working_set_bytes{phase=\"Running\",org=\"$org\",repo=\"$repo\",name=\"$job\"})",
     "legendFormat": "{{ id }}"
    }
   ]
  },
  {
   "title": "CPU Usage per Build",
   "type": "graph",
   "gridPos": { "h": 10, "w": 10, "x": 14, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (id) (prow:job:cpu_usage_seconds_rate:1m{phase=\"Running\",org=\"$org\",repo=\"$repo\",name=\"$job\"})",
     "legendFormat": "{{ id }}"
    }
   ]
  },
  {
   "title": "CPU Requested",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 15 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 * (sum (prow:job:resource_requests_cpu_cores{org=\"$org\",repo=\"$repo\",name=\"$job\"}) / sum (prow:node:cpu_capacity_cores))",
     "legendFormat": "requests"
    }
   ]
  },
  {
   "title": "CPU Used",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 2, "y": 15 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 * (sum (prow:job:cpu_usage_seconds_rate:1m{phase=\"Running\",org=\"$org\",repo=\"$repo\",name=\"$job\"}) / sum (prow:node:cpu_capacity_cores))",
     "legendFormat": "used"
    }
   ]
  },
  {
   "title": "Resource Usage for $build",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "repeat": "build",
   "collapsed": true,
   "panels": [
    {
     "title": "Memory",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum (prow:job:memory_working_set_bytes{phase=\"Running\",org=\"$org\",repo=\"$repo\",name=\"$job\",id=~\"$build\"})",
       "legendFormat": "used"
      },
      {
       "expr": "sum (prow:job:resource_requests_memory_bytes{phase=\"Running\",org=\"$org\",repo=\"$repo\",name=\"$job\",id=~\"$build\"})",
       "legendFormat": "requested"
      },
      {
       "expr": "sum (prow:job:resource_limits_memory_bytes{phase=\"Running\",org=\"$org\",repo=\"$repo\",name=\"$job\",id=~\"$build\"})",
       "legendFormat": "limit"
      }
     ]
    },
    {
     "title": "CPU",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 28 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum (prow:job:cpu_usage_seconds_rate:1m{phase=\"Running\",org=\"$org\",repo=\"$repo\",name=\"$job\",id=~\"$build\"})",
       "legendFormat": "used"
      },
      {
       "expr": "sum (prow:job:resource_requests_cpu_cores{phase=\"Running\",org=\"$org\",repo=\"$repo\",name=\"$job\",id=~\"$build\"})",
       "legendFormat": "requested"
      },
      {
       "expr": "sum (prow:job:resource_limits_cpu_cores{phase=\"Running\",org=\"$org\",repo=\"$repo\",name=\"$job\",id=~\"$build\"})",
       "legendFormat": "limit"
      }
     ]
    }
   ]
  }
 ]
}
{
 "title": "Jobs",
 "tags": [ "prow" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "org", "label": "Organisation", "query": "label_values(prow:job, org)" },
   {
    "name": "repo",
    "label": "Repository",
    "query": "label_values(prow:job{org=\"$org\"}, repo)"
   },
   {
    "name": "job",
    "query": "label_values(prow:job{org=\"$org\",repo=\"$repo\"}, name)"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Jobs",
   "type": "table",
   "gridPos": { "h": 17, "w": 4, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by (name) (prow:job{org=\"$org\",repo=\"$repo\"})"
    }
   ]
  },
  {
   "title": "Pending Jobs",
   "type": "table",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 1 },
   "targets": [
    {
     "expr": "(time() - prow:job:pending_since_time{org=\"$org\",repo=\"$repo\"}) > 60"
    }
   ]
  },
  {
   "title": "Running Jobs",
   "type": "graph",
   "gridPos": { "h": 9, "w": 11, "x": 4, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count by (name) (prow:job{phase=\"Running\",org=\"$org\",repo=\"$repo\"})",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Pending Jobs",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count by (name) (prow:job:pending{org=\"$org\",repo=\"$repo\"})",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Memory Requested",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 2, "x": 0, "y": 18 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 * (sum (prow:job:resource_requests_memory_bytes{org=\"$org\",repo=\"$repo\"}) / sum (prow:node:memory_capacity_bytes))",
     "legendFormat": "requests"
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 2, "x": 2, "y": 18 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 * (sum (prow:job:memory_working_set_bytes{phase=\"Running\",org=\"$org\",repo=\"$repo\"}) / sum (prow:node:memory_capacity_bytes))",
     "legendFormat": "used"
    }
   ]
  },
  {
   "title": "Memory Usage per Job",
   "type": "graph",
   "gridPos": { "h": 12, "w": 10, "x": 4, "y": 18 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (name) (prow:job:memory_working_set_bytes{phase=\"Running\",org=\"$org\",repo=\"$repo\"})",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "CPU Usage per Job",
   "type": "graph",
   "gridPos": { "h": 12, "w": 10, "x": 14, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (name) (prow:job:cpu_usage_seconds_rate:1m{phase=\"Running\",org=\"$org\",repo=\"$repo\"})",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "CPU Requested",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 2, "x": 0, "y": 24 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 * (sum (prow:job:resource_requests_cpu_cores{org=\"$org\",repo=\"$repo\"}) / sum (prow:node:cpu_capacity_cores))",
     "legendFormat": "requests"
    }
   ]
  },
  {
   "title": "CPU Used",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 2, "x": 2, "y": 24 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 * (sum (prow:job:cpu_usage_seconds_rate:1m{phase=\"Running\",org=\"$org\",repo=\"$repo\"}) / sum (prow:node:cpu_capacity_cores))",
     "legendFormat": "used"
    }
   ]
  },
  {
   "title": "Resource Usage for $job",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "repeat": "job",
   "collapsed": true,
   "panels": [
    {
     "title": "Memory",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum (prow:job:memory_working_set_bytes{phase=\"Running\",org=\"$org\",repo=\"$repo\",name=~\"$job\"})",
       "legendFormat": "used"
      },
      {
       "expr": "sum (prow:job:resource_requests_memory_bytes{phase=\"Running\",org=\"$org\",repo=\"$repo\",name=~\"$job\"})",
       "legendFormat": "requested"
      },
      {
       "expr": "sum (prow:job:resource_limits_memory_bytes{phase=\"Running\",org=\"$org\",repo=\"$repo\",name=~\"$job\"})",
       "legendFormat": "limit"
      }
     ]
    },
    {
     "title": "CPU",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 31 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum (prow:job:cpu_usage_seconds_rate:1m{phase=\"Running\",org=\"$org\",repo=\"$repo\",name=~\"$job\"})",
       "legendFormat": "used"
      },
      {
       "expr": "sum (prow:job:resource_requests_cpu_cores{phase=\"Running\",org=\"$org\",repo=\"$repo\",name=~\"$job\"})",
       "legendFormat": "requested"
      },
      {
       "expr": "sum (prow:job:resource_limits_cpu_cores{phase=\"Running\",org=\"$org\",repo=\"$repo\",name=~\"$job\"})",
       "legendFormat": "limit"
      }
     ]
    }
   ]
  }
 ]
}
{
 "title": "Organisations",
 "tags": [ "prow" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "org", "query": "label_values(prow:job, org)" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Organisations",
   "type": "table",
   "gridPos": { "h": 17, "w": 4, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by (org) (prow:job{org!=\"\"})"
    }
   ]
  },
  {
   "title": "Pending Jobs",
   "type": "table",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 1 },
   "targets": [
    {
     "expr": "(time() - prow:job:pending_since_time) > 60"
    }
   ]
  },
  {
   "title": "Running Jobs",
   "type": "graph",
   "gridPos": { "h": 9, "w": 10, "x": 4, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count by (org) (prow:job{phase=\"Running\",org!=\"\"})",
     "legendFormat": "{{ org }}"
    },
    {
     "expr": "count (prow:job:pending{phase=\"Running\",org=\"\"})",
     "legendFormat": "(no org)"
    }
   ]
  },
  {
   "title": "Pending Jobs",
   "type": "graph",
   "gridPos": { "h": 9, "w": 10, "x": 14, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count by (org) (prow:job:pending{org!=\"\"})",
     "legendFormat": "{{ org }}"
    },
    {
     "expr": "count (prow:job:pending{org=\"\"})",
     "legendFormat": "(no org)"
    }
   ]
  },
  {
   "title": "Memory Requested",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 18 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 * (sum (prow:job:resource_requests_memory_bytes) / sum (prow:node:memory_capacity_bytes))",
     "legendFormat": "requests"
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 2, "y": 18 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 * (sum (prow:job:memory_working_set_bytes{phase=\"Running\"}) / sum (prow:node:memory_capacity_bytes))",
     "legendFormat": "used"
    }
   ]
  },
  {
   "title": "Memory Usage per Organisation",
   "type": "graph",
   "gridPos": { "h": 10, "w": 10, "x": 4, "y": 18 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (org) (prow:job:memory_working_set_bytes{phase=\"Running\"})",
     "legendFormat": "{{ org }}"
    }
   ]
  },
  {
   "title": "CPU Usage per Organisation",
   "type": "graph",
   "gridPos": { "h": 10, "w": 10, "x": 14, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (org) (prow:job:cpu_usage_seconds_rate:1m{phase=\"Running\"})",
     "legendFormat": "{{ org }}"
    }
   ]
  },
  {
   "title": "CPU Requested",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 23 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 * (sum (prow:job:resource_requests_cpu_cores) / sum (prow:node:cpu_capacity_cores))",
     "legendFormat": "requests"
    }
   ]
  },
  {
   "title": "CPU Used",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 2, "y": 23 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 * (sum (prow:job:cpu_usage_seconds_rate:1m{phase=\"Running\"}) / sum (prow:node:cpu_capacity_cores))",
     "legendFormat": "used"
    }
   ]
  },
  {
   "title": "Resource Usage not attributed to any organisation",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum (prow:job:memory_working_set_bytes{phase=\"Running\",org=\"\"})",
       "legendFormat": "used"
      },
      {
       "expr": "sum (prow:job:resource_requests_memory_bytes{phase=\"Running\",org=\"\"})",
       "legendFormat": "requested"
      },
      {
       "expr": "sum (prow:job:resource_limits_memory_bytes{phase=\"Running\",org=\"\"})",
       "legendFormat": "limit"
      }
     ]
    },
    {
     "title": "CPU",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum (prow:job:cpu_usage_seconds_rate:1m{phase=\"Running\",org=\"\"})",
       "legendFormat": "used"
      },
      {
       "expr": "sum (prow:job:resource_requests_cpu_cores{phase=\"Running\",org=\"\"})",
       "legendFormat": "requested"
      },
      {
       "expr": "sum (prow:job:resource_limits_cpu_cores{phase=\"Running\",org=\"\"})",
       "legendFormat": "limit"
      }
     ]
    }
   ]
  },
  {
   "title": "Resource Usage for $org",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "repeat": "org",
   "collapsed": true,
   "panels": [
    {
     "title": "Memory",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum (prow:job:memory_working_set_bytes{phase=\"Running\",org=~\"$org\"})",
       "legendFormat": "used"
      },
      {
       "expr": "sum (prow:job:resource_requests_memory_bytes{phase=\"Running\",org=~\"$org\"})",
       "legendFormat": "requested"
      },
      {
       "expr": "sum (prow:job:resource_limits_memory_bytes{phase=\"Running\",org=~\"$org\"})",
       "legendFormat": "limit"
      }
     ]
    },
    {
     "title": "CPU",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 21 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum (prow:job:cpu_usage_seconds_rate:1m{phase=\"Running\",org=~\"$org\"})",
       "legendFormat": "used"
      },
      {
       "expr": "sum (prow:job:resource_requests_cpu_cores{phase=\"Running\",org=~\"$org\"})",
       "legendFormat": "requested"
      },
      {
       "expr": "sum (prow:job:resource_limits_cpu_cores{phase=\"Running\",org=~\"$org\"})",
       "legendFormat": "limit"
      }
     ]
    }
   ]
  }
 ]
}
{
 "title": "Repositories",
 "tags": [ "prow" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "org", "label": "Organisation", "query": "label_values(prow:job, org)" },
   {
    "name": "repo",
    "query": "label_values(prow:job{org=\"$org\"}, repo)"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Repositories",
   "type": "table",
   "gridPos": { "h": 17, "w": 4, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by (repo) (prow:job{org=\"$org\"})"
    }
   ]
  },
  {
   "title": "Pending Jobs",
   "type": "table",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 1 },
   "targets": [
    {
     "expr": "(time() - prow:job:pending_since_time{repo=~\"$repo\"}) > 60"
    }
   ]
  },
  {
   "title": "Running Jobs",
   "type": "graph",
   "gridPos": { "h": 9, "w": 10, "x": 4, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count by (repo) (prow:job{phase=\"Running\",org=\"$org\"})",
     "legendFormat": "{{ repo }}"
    }
   ]
  },
  {
   "title": "Pending Jobs",
   "type": "graph",
   "gridPos": { "h": 9, "w": 10, "x": 14, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count by (repo) (prow:job:pending{org=\"$org\"})",
     "legendFormat": "{{ repo }}"
    }
   ]
  },
  {
   "title": "Memory Requested",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 18 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 * (sum (prow:job:resource_requests_memory_bytes{org=\"$org\"}) / sum (prow:node:memory_capacity_bytes))",
     "legendFormat": "requests"
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 2, "y": 18 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 * (sum (prow:job:memory_working_set_bytes{phase=\"Running\",org=\"$org\"}) / sum (prow:node:memory_capacity_bytes))",
     "legendFormat": "used"
    }
   ]
  },
  {
   "title": "Memory Usage per Repository",
   "type": "graph",
   "gridPos": { "h": 10, "w": 10, "x": 4, "y": 18 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (repo) (prow:job:memory_working_set_bytes{phase=\"Running\",org=\"$org\"})",
     "legendFormat": "{{ repo }}"
    }
   ]
  },
  {
   "title": "CPU Usage per Repository",
   "type": "graph",
   "gridPos": { "h": 10, "w": 10, "x": 14, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (repo) (prow:job:cpu_usage_seconds_rate:1m{phase=\"Running\",org=\"$org\"})",
     "legendFormat": "{{ repo }}"
    }
   ]
  },
  {
   "title": "CPU Requested",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 23 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 * (sum (prow:job:resource_requests_cpu_cores{org=\"$org\"}) / sum (prow:node:cpu_capacity_cores))",
     "legendFormat": "requests"
    }
   ]
  },
  {
   "title": "CPU Used",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 2, "y": 23 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 * (sum (prow:job:cpu_usage_seconds_rate:1m{phase=\"Running\",org=\"$org\"}) / sum (prow:node:cpu_capacity_cores))",
     "legendFormat": "used"
    }
   ]
  },
  {
   "title": "Resource Usage for $repo",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "repeat": "repo",
   "collapsed": true,
   "panels": [
    {
     "title": "Memory",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum (prow:job:memory_working_set_bytes{phase=\"Running\",org=\"$org\",repo=~\"$repo\"})",
       "legendFormat": "used"
      },
      {
       "expr": "sum (prow:job:resource_requests_memory_bytes{phase=\"Running\",org=\"$org\",repo=~\"$repo\"})",
       "legendFormat": "requested"
      },
      {
       "expr": "sum (prow:job:resource_limits_memory_bytes{phase=\"Running\",org=\"$org\",repo=~\"$repo\"})",
       "legendFormat": "limit"
      }
     ]
    },
    {
     "title": "CPU",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 28 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum (prow:job:cpu_usage_seconds_rate:1m{phase=\"Running\",org=\"$org\",repo=~\"$repo\"})",
       "legendFormat": "used"
      },
      {
       "expr": "sum (prow:job:resource_requests_cpu_cores{phase=\"Running\",org=\"$org\",repo=~\"$repo\"})",
       "legendFormat": "requested"
      },
      {
       "expr": "sum (prow:job:resource_limits_cpu_cores{phase=\"Running\",org=\"$org\",repo=~\"$repo\"})",
       "legendFormat": "limit"
      }
     ]
    }
   ]
  }
 ]
}