# ---
# kind: ServiceAccount
# apiVersion: v1
# metadata:
#   annotations:
#     iam.gke.io/gcp-service-account: pusher@k8s-prow.iam.gserviceaccount.com
#   name: pusher
#   namespace: test-pods
# ---
# kind: ServiceAccount
# apiVersion: v1
# metadata:
#   annotations:
#     iam.gke.io/gcp-service-account: testgrid-config-updater@k8s-testgrid.iam.gserviceaccount.com
#   name: testgrid-config-updater
#   namespace: test-pods
# ---
# kind: ServiceAccount
# apiVersion: v1
# metadata:
#   annotations:
#     iam.gke.io/gcp-service-account: deployer@k8s-prow.iam.gserviceaccount.com
#   name: deployer
#   namespace: test-pods
# ---
# kind: ServiceAccount
# apiVersion: v1
# metadata:
#   annotations:
#     iam.gke.io/gcp-service-account: gencred-refresher@k8s-prow.iam.gserviceaccount.com
#   name: gencred-refresher
#   namespace: test-pods
# ---
# kind: ServiceAccount
# apiVersion: v1
# metadata:
#   annotations:
#     iam.gke.io/gcp-service-account: k8s-infra-gcr-promoter@k8s-artifacts-prod.iam.gserviceaccount.com
#   name: k8s-infra-gcr-promoter
#   namespace: test-pods
# ---
# kind: ServiceAccount
# apiVersion: v1
# metadata:
#   annotations:
#     iam.gke.io/gcp-service-account: k8s-infra-gcr-promoter@k8s-artifacts-prod-bak.iam.gserviceaccount.com
#   name: k8s-infra-gcr-promoter-bak
#   namespace: test-pods
# ---
# kind: ServiceAccount
# apiVersion: v1
# metadata:
#   annotations:
#     iam.gke.io/gcp-service-account: kubernetes-external-secrets-sa@k8s-prow.iam.gserviceaccount.com
#   name: kubernetes-external-secrets-sa
#   namespace: default
# ---
# kind: ServiceAccount
# apiVersion: v1
# metadata:
#   annotations:
#     iam.gke.io/gcp-service-account: prowjob-default-sa@k8s-prow.iam.gserviceaccount.com
#   name: prowjob-default-sa
#   namespace: test-pods
# ---
# # legacy-sa-json-key-rotator is used for rotating the default build cluster sa
# # json key, and should only be used for this purpose. This GCP SA will be
# # granted secret manager owner permission on the
# # default-k8s-build-cluster-service-account-key secret in k8s-prow-builds
# # project, and service account key list/create/delete permission on the
# # pr-kubekins@kubernetes-jenkins-pull.iam.gserviceaccount.com SA.
# kind: ServiceAccount
# apiVersion: v1
# metadata:
#   annotations:
#     iam.gke.io/gcp-service-account: legacy-sa-json-key-rotator@k8s-prow.iam.gserviceaccount.com
#   name: legacy-sa-json-key-rotator
#   namespace: test-pods
