{
 "title": "Fastly Security",
 "tags": [
  "fastly",
  "security"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "DDoS Mitigation Count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(fastly_rt_ddos_protection_requests_mitigate_total[120s])) by (service_id,service_name)",
     "legendFormat": "{{service_name}} ({{service_id}})"
    }
   ]
  },
  {
   "title": "Bot Challenges Failed",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(fastly_rt_bot_challenges_failed_total[120s])) by (service_id,service_name)",
     "legendFormat": "{{service_name}} ({{service_id}})"
    }
   ]
  },
  {
   "title": "Attack Blocked Req Body Bytes",
   "type": "stat",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(fastly_rt_attack_blocked_req_body_bytes_total[120s])) by (service_id,service_name)",
     "legendFormat": "{{service_name}} ({{service_id}})"
    }
   ]
  }
 ]
}