{
 "title": "Fastly Compute",
 "tags": [
  "fastly",
  "compute"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "service_name", "label": "Service Name", "query": "label_values(service_name)" },
   { "name": "service_id", "label": "Service ID", "query": "label_values(service_id)" },
   {
    "name": "datacenter",
    "label": "POP",
    "query": "label_values(fastly_rt_compute_requests_total, datacenter)"
   },
   {
    "name": "rate",
    "label": "Rate",
    "query": "30s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "HEALTH", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "2XX",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(fastly_rt_compute_resp_status_total{service_name=~\"$service_name\", service_id=~\"$service_id\", datacenter=~\"$datacenter\", status_group=\"2xx\"}[$rate])) / sum(rate(fastly_rt_compute_requests_total{service_name=~\"$service_name\", service_id=~\"$service_id\", datacenter=~\"$datacenter\"}[$rate]))"
    }
   ]
  },
  {
   "title": "3XX",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(fastly_rt_compute_resp_status_total{service_name=~\"$service_name\", service_id=~\"$service_id\", datacenter=~\"$datacenter\", status_group=\"3xx\"}[$rate])) / sum(rate(fastly_rt_compute_requests_total{service_name=~\"$service_name\", service_id=~\"$service_id\", datacenter=~\"$datacenter\"}[$rate]))"
    }
   ]
  },
  {
   "title": "4XX",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(fastly_rt_compute_resp_status_total{service_name=~\"$service_name\", service_id=~\"$service_id\", datacenter=~\"$datacenter\", status_group=\"4xx\"}[$rate])) / sum(rate(fastly_rt_compute_requests_total{service_name=~\"$service_name\", service_id=~\"$service_id\", datacenter=~\"$datacenter\"}[$rate]))"
    }
   ]
  },
  {
   "title": "5XX",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(fastly_rt_compute_resp_status_total{service_name=~\"$service_name\", service_id=~\"$service_id\", datacenter=~\"$datacenter\", status_group=\"5xx\"}[$rate])) / sum(rate(fastly_rt_compute_requests_total{service_name=~\"$service_name\", service_id=~\"$service_id\", datacenter=~\"$datacenter\"}[$rate]))"
    }
   ]
  },
  {
   "title": "COMPUTE ERRORS",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(sum(rate(fastly_rt_compute_guest_errors_total{service_name=~\"$service_name\", service_id=~\"$service_id\", datacenter=~\"$datacenter\"}[$rate])) + sum(rate(fastly_rt_compute_runtime_errors_total{service_name=~\"$service_name\", service_id=~\"$service_id\", datacenter=~\"$datacenter\"}[$rate]))) / sum(rate(fastly_rt_compute_requests_total{service_name=~\"$service_name\", service_id=~\"$service_id\", datacenter=~\"$datacenter\"}[$rate]))"
    }
   ]
  },
  {
   "title": "REQ HEADER",
   "type": "stat",
   "description": "69KB limit per https://docs.fastly.com/en/guides/resource-limits#request-and-header-limits",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(fastly_rt_compute_req_header_bytes_total{service_name=~\"$service_name\", service_id=~\"$service_id\", datacenter=~\"$datacenter\"}[$rate])) / sum(rate(fastly_rt_compute_requests_total{service_name=~\"$service_name\", service_id=~\"$service_id\", datacenter=~\"$datacenter\"}[$rate])) / 69000"
    }
   ]
  },
  {
   "title": "RESP HEADER",
   "type": "stat",
   "description": "69KB limit per https://docs.fastly.com/en/guides/resource-limits#request-and-header-limits",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(fastly_rt_compute_resp_header_bytes_total{service_name=~\"$service_name\", service_id=~\"$service_id\", datacenter=~\"$datacenter\"}[$rate])) / sum(rate(fastly_rt_compute_requests_total{service_name=~\"$service_name\", service_id=~\"$service_id\", datacenter=~\"$datacenter\"}[$rate])) / 69000"
    }
   ]
  },
  {
   "title": "Avg Execution Time",
   "type": "stat",
   "description": "Thresholds from https://www.littledata.io/average/server-response-time",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(fastly_rt_compute_execution_time_total{service_name=~\"$service_name\", service_id=~\"$service_id\", datacenter=~\"$datacenter\"}[$rate])) / sum(rate(fastly_rt_compute_requests_total{service_name=~\"$service_name\", service_id=~\"$service_id\", datacenter=~\"$datacenter\"}[$rate]))"
    }
   ]
  },
  { "title": "RESOURCE USAGE", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Resource Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(fastly_rt_compute_ram_used_bytes_total{service_name=~\"$service_name\", service_id=~\"$service_id\", datacenter=~\"$datacenter\"}[$rate]))",
     "legendFormat": "RAM Used"
    }
   ]
  },
  { "title": "RESOURCE LIMITS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Resource Limits Exceeded",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum(rate(fastly_rt_compute_heap_limit_exceeded_total{service_name=~\"$service_name\", service_id=~\"$service_id\", datacenter=~\"$datacenter\"}[$rate]))",
     "legendFormat": "Heap Limit Exceeded"
    },
    {
     "expr": "sum(rate(fastly_rt_compute_globals_limit_exceeded_total{service_name=~\"$service_name\", service_id=~\"$service_id\", datacenter=~\"$datacenter\"}[$rate]))",
     "legendFormat": "Globals Limit Exceeded"
    },
    {
     "expr": "sum(rate(fastly_rt_compute_stack_limit_exceeded_total{service_name=~\"$service_name\", service_id=~\"$service_id\", datacenter=~\"$datacenter\"}[$rate]))",
     "legendFormat": "Stack Limit Exceeded"
    },
    {
     "expr": "sum(rate(fastly_rt_compute_resource_limit_exceeded_total{service_name=~\"$service_name\", service_id=~\"$service_id\", datacenter=~\"$datacenter\"}[$rate]))",
     "legendFormat": "Resource Limit Exceeded"
    }
   ]
  },
  { "title": "BACKEND REQUESTS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Backend Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(fastly_rt_compute_bereq_total{service_name=~\"$service_name\", service_id=~\"$service_id\", datacenter=~\"$datacenter\"}[$rate]))",
     "legendFormat": "Backend Requests"
    },
    {
     "expr": "sum(rate(fastly_rt_compute_bereq_body_bytes_total{service_name=~\"$service_name\", service_id=~\"$service_id\", datacenter=~\"$datacenter\"}[$rate]))",
     "legendFormat": "Backend Request Body Bytes"
    },
    {
     "expr": "sum(rate(fastly_rt_compute_bereq_header_bytes_total{service_name=~\"$service_name\", service_id=~\"$service_id\", datacenter=~\"$datacenter\"}[$rate]))",
     "legendFormat": "Backend Request Header Bytes"
    }
   ]
  },
  { "title": "RESPONSE/REQUEST METRICS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Response/Request Metrics",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(fastly_rt_compute_resp_body_bytes_total{service_name=~\"$service_name\", service_id=~\"$service_id\", datacenter=~\"$datacenter\"}[$rate]))",
     "legendFormat": "Response Body Bytes"
    },
    {
     "expr": "sum(rate(fastly_rt_compute_resp_header_bytes_total{service_name=~\"$service_name\", service_id=~\"$service_id\", datacenter=~\"$datacenter\"}[$rate]))",
     "legendFormat": "Response Header Bytes"
    },
    {
     "expr": "sum(rate(fastly_rt_compute_req_body_bytes_total{service_name=~\"$service_name\", service_id=~\"$service_id\", datacenter=~\"$datacenter\"}[$rate]))",
     "legendFormat": "Request Body Bytes"
    },
    {
     "expr": "sum(rate(fastly_rt_compute_req_header_bytes_total{service_name=~\"$service_name\", service_id=~\"$service_id\", datacenter=~\"$datacenter\"}[$rate]))",
     "legendFormat": "Request Header Bytes"
    }
   ]
  }
 ]
}