title: Access Logs
description: View access to GCP access logs
name: access-logs.viewer
include:
  roles:
  - roles/compute.viewer
  - roles/dns.reader
  - roles/iam.securityReviewer
  - roles/resourcemanager.organizationViewer
  - roles/serviceusage.serviceUsageConsumer
  permissions:
  - storage.buckets.get
  - storage.buckets.getIamPolicy
  - storage.buckets.list
