apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: default
spec:
  role: "karpenter-nodes"
  instanceStorePolicy: RAID0
  amiFamily: Bottlerocket
  amiSelectorTerms:
    - alias: bottlerocket@latest
  detailedMonitoring: true
  associatePublicIPAddress: true
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: "prow-build-cluster"
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: "prow-build-cluster"
  tags:
    Cluster: prow-build-cluster
  userData: |
    # https://bottlerocket.dev/en/os/1.62.x/api/settings/kubernetes/
    [settings.kubernetes]
    single-process-oom-kill = true
    [settings.host-containers.admin]
    enabled = true
    [settings.kernel.sysctl]
    "fs.inotify.max_user_watches" = "1048576"
    "fs.inotify.max_user_instances" = "8192"
    "vm.min_free_kbytes" = "540672"
