settings:
  clusterName: prow-build-cluster
  interruptionQueue: karpenter-queue

controller:
  resources:
    requests:
      cpu: 1
      memory: 1Gi
    limits:
      cpu: 1
      memory: 1Gi

nodeSelector:
  kubernetes.io/os: linux
  node-group: stable

podAnnotations:
  ad.datadoghq.com/controller.logs: '[{"source": "karpenter", "service": "karpenter"}]'
  ad.datadoghq.com/controller.checks: |
    {
      "karpenter": {
        "init_config": {},
        "instances": [
          {
            "openmetrics_endpoint": "http://%%host%%:8080/metrics"
          }
        ]
      }
    }

tolerations:
  - effect: NoSchedule
    key: node-group
    operator: Equal
    value: stable
