apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: amd64-latest
spec:
  weight: 100
  template:
    spec:
      expireAfter: 720h
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: default
      requirements:
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["on-demand"]
        - key: topology.kubernetes.io/zone
          operator: In
          values: ["us-east-2a", "us-east-2b", "us-east-2c"]
        - key: kubernetes.io/arch
          operator: In
          values: ["amd64"]
        - key: node.kubernetes.io/instance-type
          operator: In
          values:
            - m8id.2xlarge
            - m8idb.2xlarge
            - m8idn.2xlarge
  limits:
    cpu: "2400" # 300 VMs
  disruption:
    consolidationPolicy: WhenEmpty
    consolidateAfter: 20m
    budgets:
      - nodes: "20%" # Allowing rotating 20% of instances at any given time
---
# The new generation instances are capacity constrained, create older-nodes if necessary
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: amd64-fallback
spec:
  weight: 10
  template:
    spec:
      expireAfter: 720h
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: default
      requirements:
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["on-demand"]
        - key: topology.kubernetes.io/zone
          operator: In
          values: ["us-east-2a", "us-east-2b", "us-east-2c"]
        - key: kubernetes.io/arch
          operator: In
          values: ["amd64"]
        - key: node.kubernetes.io/instance-type
          operator: In
          values:
            - m6id.2xlarge
            - m6idn.2xlarge
  limits:
    cpu: "400" # 50 VMs
  disruption:
    consolidationPolicy: WhenEmpty
    consolidateAfter: 30s
    budgets:
      - nodes: "20%" # Allowing rotating 20% of instances at any given time
---
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: arm64
spec:
  template:
    spec:
      expireAfter: 720h
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: default
      taints:
        - key: kubernetes.io/arch
          value: arm64
          effect: NoSchedule
      requirements:
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["on-demand"]
        - key: topology.kubernetes.io/zone
          operator: In
          values: ["us-east-2a", "us-east-2b", "us-east-2c"]
        - key: kubernetes.io/arch
          operator: In
          values: ["arm64"]
        - key: node.kubernetes.io/instance-type
          operator: In
          values:
           - m8gd.2xlarge
           - m9gd.2xlarge
  limits:
    cpu: "1200" # 150 x m7gd.2xlarge (8 vCPUs)
  disruption:
    consolidationPolicy: WhenEmpty
    consolidateAfter: 5m
    budgets:
      - nodes: "20%" # Allowing rotating 20% of instances at any given time
