apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kops-discovery
spec:
  secretName: kops-discovery-cert
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - discovery.kops.k8s.io
