apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mimir-credentials
  namespace: monitoring
spec:
  target:
    name: mimir-credentials
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: mimir-credentials
        property: username
    - secretKey: password
      remoteRef:
        key: mimir-credentials
        property: password
  secretStoreRef:
    kind: ClusterSecretStore
    name: k8s-infra-prow-build
