// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.12.4
// source: pkg/ipinfo/ipinfopb/ipinfo.proto

package ipinfopb

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type CIDRInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cidr                  string `protobuf:"bytes,1,opt,name=cidr,proto3" json:"cidr,omitempty"`
	Entity                string `protobuf:"bytes,2,opt,name=entity,proto3" json:"entity,omitempty"`
	Service               string `protobuf:"bytes,3,opt,name=service,proto3" json:"service,omitempty"`
	Region                string `protobuf:"bytes,4,opt,name=region,proto3" json:"region,omitempty"`
	AwsNetworkBorderGroup string `protobuf:"bytes,5,opt,name=aws_network_border_group,json=awsNetworkBorderGroup,proto3" json:"aws_network_border_group,omitempty"`
}

func (x *CIDRInfo) Reset() {
	*x = CIDRInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_ipinfo_ipinfopb_ipinfo_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CIDRInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CIDRInfo) ProtoMessage() {}

func (x *CIDRInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_ipinfo_ipinfopb_ipinfo_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CIDRInfo.ProtoReflect.Descriptor instead.
func (*CIDRInfo) Descriptor() ([]byte, []int) {
	return file_pkg_ipinfo_ipinfopb_ipinfo_proto_rawDescGZIP(), []int{0}
}

func (x *CIDRInfo) GetCidr() string {
	if x != nil {
		return x.Cidr
	}
	return ""
}

func (x *CIDRInfo) GetEntity() string {
	if x != nil {
		return x.Entity
	}
	return ""
}

func (x *CIDRInfo) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *CIDRInfo) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *CIDRInfo) GetAwsNetworkBorderGroup() string {
	if x != nil {
		return x.AwsNetworkBorderGroup
	}
	return ""
}

type CIDRMap struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cidrs []*CIDRInfo `protobuf:"bytes,1,rep,name=cidrs,proto3" json:"cidrs,omitempty"`
}

func (x *CIDRMap) Reset() {
	*x = CIDRMap{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_ipinfo_ipinfopb_ipinfo_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CIDRMap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CIDRMap) ProtoMessage() {}

func (x *CIDRMap) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_ipinfo_ipinfopb_ipinfo_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CIDRMap.ProtoReflect.Descriptor instead.
func (*CIDRMap) Descriptor() ([]byte, []int) {
	return file_pkg_ipinfo_ipinfopb_ipinfo_proto_rawDescGZIP(), []int{1}
}

func (x *CIDRMap) GetCidrs() []*CIDRInfo {
	if x != nil {
		return x.Cidrs
	}
	return nil
}

var File_pkg_ipinfo_ipinfopb_ipinfo_proto protoreflect.FileDescriptor

var file_pkg_ipinfo_ipinfopb_ipinfo_proto_rawDesc = []byte{
	0x0a, 0x20, 0x70, 0x6b, 0x67, 0x2f, 0x69, 0x70, 0x69, 0x6e, 0x66, 0x6f, 0x2f, 0x69, 0x70, 0x69,
	0x6e, 0x66, 0x6f, 0x70, 0x62, 0x2f, 0x69, 0x70, 0x69, 0x6e, 0x66, 0x6f, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x08, 0x69, 0x70, 0x69, 0x6e, 0x66, 0x6f, 0x70, 0x62, 0x22, 0xa1, 0x01, 0x0a,
	0x08, 0x43, 0x49, 0x44, 0x52, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x69, 0x64,
	0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x69, 0x64, 0x72, 0x12, 0x16, 0x0a,
	0x06, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x65,
	0x6e, 0x74, 0x69, 0x74, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x16, 0x0a, 0x06, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x12, 0x37, 0x0a, 0x18, 0x61, 0x77, 0x73, 0x5f, 0x6e,
	0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x5f, 0x62, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f, 0x67, 0x72,
	0x6f, 0x75, 0x70, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x15, 0x61, 0x77, 0x73, 0x4e, 0x65,
	0x74, 0x77, 0x6f, 0x72, 0x6b, 0x42, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x47, 0x72, 0x6f, 0x75, 0x70,
	0x22, 0x33, 0x0a, 0x07, 0x43, 0x49, 0x44, 0x52, 0x4d, 0x61, 0x70, 0x12, 0x28, 0x0a, 0x05, 0x63,
	0x69, 0x64, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x69, 0x70, 0x69,
	0x6e, 0x66, 0x6f, 0x70, 0x62, 0x2e, 0x43, 0x49, 0x44, 0x52, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x05,
	0x63, 0x69, 0x64, 0x72, 0x73, 0x42, 0x3e, 0x5a, 0x3c, 0x6b, 0x38, 0x73, 0x2e, 0x69, 0x6f, 0x2f,
	0x6b, 0x38, 0x73, 0x2e, 0x69, 0x6f, 0x2f, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x2f, 0x61,
	0x63, 0x63, 0x65, 0x73, 0x73, 0x2d, 0x6c, 0x6f, 0x67, 0x73, 0x2f, 0x6c, 0x6f, 0x61, 0x64, 0x65,
	0x72, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x69, 0x70, 0x69, 0x6e, 0x66, 0x6f, 0x2f, 0x69, 0x70, 0x69,
	0x6e, 0x66, 0x6f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_ipinfo_ipinfopb_ipinfo_proto_rawDescOnce sync.Once
	file_pkg_ipinfo_ipinfopb_ipinfo_proto_rawDescData = file_pkg_ipinfo_ipinfopb_ipinfo_proto_rawDesc
)

func file_pkg_ipinfo_ipinfopb_ipinfo_proto_rawDescGZIP() []byte {
	file_pkg_ipinfo_ipinfopb_ipinfo_proto_rawDescOnce.Do(func() {
		file_pkg_ipinfo_ipinfopb_ipinfo_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_ipinfo_ipinfopb_ipinfo_proto_rawDescData)
	})
	return file_pkg_ipinfo_ipinfopb_ipinfo_proto_rawDescData
}

var file_pkg_ipinfo_ipinfopb_ipinfo_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pkg_ipinfo_ipinfopb_ipinfo_proto_goTypes = []interface{}{
	(*CIDRInfo)(nil), // 0: ipinfopb.CIDRInfo
	(*CIDRMap)(nil),  // 1: ipinfopb.CIDRMap
}
var file_pkg_ipinfo_ipinfopb_ipinfo_proto_depIdxs = []int32{
	0, // 0: ipinfopb.CIDRMap.cidrs:type_name -> ipinfopb.CIDRInfo
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pkg_ipinfo_ipinfopb_ipinfo_proto_init() }
func file_pkg_ipinfo_ipinfopb_ipinfo_proto_init() {
	if File_pkg_ipinfo_ipinfopb_ipinfo_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_ipinfo_ipinfopb_ipinfo_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CIDRInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_ipinfo_ipinfopb_ipinfo_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CIDRMap); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_ipinfo_ipinfopb_ipinfo_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_ipinfo_ipinfopb_ipinfo_proto_goTypes,
		DependencyIndexes: file_pkg_ipinfo_ipinfopb_ipinfo_proto_depIdxs,
		MessageInfos:      file_pkg_ipinfo_ipinfopb_ipinfo_proto_msgTypes,
	}.Build()
	File_pkg_ipinfo_ipinfopb_ipinfo_proto = out.File
	file_pkg_ipinfo_ipinfopb_ipinfo_proto_rawDesc = nil
	file_pkg_ipinfo_ipinfopb_ipinfo_proto_goTypes = nil
	file_pkg_ipinfo_ipinfopb_ipinfo_proto_depIdxs = nil
}
