#!/usr/bin/env bash
# Copyright 2026 The Kubernetes Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Regenerates kubernetes/gke-prow-build-trusted/prow/builds-sa.yaml from
# local.registries in infra/gcp/terraform/k8s-staging-images/registries.tf.
#
# This produces the same output as `local_file.builds_sa` in that terraform
# module, so it can be used to refresh the manifest without a terraform apply.

set -o errexit
set -o nounset
set -o pipefail

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd )"

REGISTRIES_TF="${REPO_ROOT}/infra/gcp/terraform/k8s-staging-images/registries.tf"
OUTPUT="${REPO_ROOT}/kubernetes/gke-prow-build-trusted/prow/builds-sa.yaml"
PROJECT="k8s-staging-images"

function usage() {
    echo "usage: $0 [--verify]" > /dev/stderr
    echo "  regenerates ${OUTPUT#"${REPO_ROOT}/"} from local.registries" > /dev/stderr
    echo "  --verify: fail if the file is out of date instead of writing it" > /dev/stderr
    echo > /dev/stderr
}

verify="false"
case "${1:-}" in
    "") ;;
    --verify) verify="true" ;;
    *) usage; exit 1 ;;
esac

# Extract the keys of the `registries = { ... }` map.
function registry_names() {
    awk '
        /^[[:space:]]*registries[[:space:]]*=[[:space:]]*\{/ { in_map = 1; next }
        in_map && /^[[:space:]]*\}/                          { exit }
        in_map && /=/                                        { print $1 }
    ' "${REGISTRIES_TF}" | sort
}

function generate() {
    cat <<EOF
# GENERATED FILE - DO NOT EDIT
# Generated by hack/generate-staging-builds-sa.sh
# Prow build service accounts for ${PROJECT} registries.
EOF

    local name gsa
    while read -r name; do
        # google_service_account.build_sa uses account_id = substr(name, 0, 27)
        gsa="${name:0:27}-sa"
        cat <<EOF
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ${name}
  annotations:
    iam.gke.io/gcp-service-account: ${gsa}@${PROJECT}.iam.gserviceaccount.com
EOF
    done < <(registry_names)
}

if [ ! -f "${REGISTRIES_TF}" ]; then
    echo >/dev/stderr "ERROR: could not find ${REGISTRIES_TF}"
    exit 1
fi

if [ "$(registry_names | wc -l)" -eq 0 ]; then
    echo >/dev/stderr "ERROR: no registries found in ${REGISTRIES_TF}"
    exit 1
fi

if [ "${verify}" == "true" ]; then
    if ! diff -u "${OUTPUT}" <(generate); then
        echo >/dev/stderr "ERROR: ${OUTPUT#"${REPO_ROOT}/"} is out of date - run $0"
        exit 1
    fi
    echo "${OUTPUT#"${REPO_ROOT}/"} is up to date"
    exit 0
fi

generate > "${OUTPUT}"
echo "wrote ${OUTPUT#"${REPO_ROOT}/"}"
