apiVersion: kyverno.io/v1
kind: Policy
metadata:
  name: prow
spec:
  background: false
  rules:
    - name: add-prow-sidecar-creds
      match:
        any:
          - resources:
              kinds:
                - Pod
              operations:
                - CREATE # we want to ignore prow update operations
      preconditions:
        all:
          - key: '{{request.object.metadata.labels."created-by-prow" || ""}}'
            operator: Equals
            value: "true"
          - key: initupload
            operator: In
            value: "{{ request.object.spec.initContainers[].name || `[]` }}"
          - key: test
            operator: In
            value: "{{ request.object.spec.containers[].name || `[]` }}"
          - key: sidecar
            operator: In
            value: "{{ request.object.spec.containers[].name || `[]` }}"
      mutate:
        foreach:
          - list: "request.object.spec.initContainers[?name=='clonerefs'] || `[]`"
            patchStrategicMerge:
              spec:
                initContainers:
                  # pod order matters
                  - name: clonerefs
                  - (name): "initupload"
                    env:
                      - name: GOOGLE_APPLICATION_CREDENTIALS
                        value: /etc/google/adc.json
                    volumeMounts: &volumeMounts
                      - mountPath: /var/run/secrets/google-iam-token/serviceaccount
                        name: google-iam-token
                        readOnly: true
                      - mountPath: /etc/google
                        name: google-adc
                        readOnly: true
                containers: &containers
                  - name: test
                  - (name): sidecar
                    env:
                      - name: GOOGLE_APPLICATION_CREDENTIALS
                        value: /etc/google/adc.json
                    volumeMounts:
                      - mountPath: /var/run/secrets/google-iam-token/serviceaccount
                        name: google-iam-token
                        readOnly: true
                      - mountPath: /etc/google
                        name: google-adc
                        readOnly: true
                volumes: &volumes
                  - name: google-iam-token
                    projected:
                      defaultMode: 420
                      sources:
                        - serviceAccountToken:
                            audience: sts.googleapis.com
                            expirationSeconds: 86400
                            path: token
                  - name: google-adc
                    configMap:
                      name: google-adc
          - list: "request.object.spec.initContainers[?name=='initupload'] || `[]`"
            preconditions:
              all:
                - key: clonerefs
                  operator: NotIn
                  value: "{{ request.object.spec.initContainers[].name || `[]` }}"
            patchStrategicMerge:
              spec:
                initContainers:
                  - (name): "initupload"
                    env:
                      - name: GOOGLE_APPLICATION_CREDENTIALS
                        value: /etc/google/adc.json
                    volumeMounts: *volumeMounts
                containers: *containers
                volumes: *volumes
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: google-adc
data:
  adc.json: |
    {
      "universe_domain": "googleapis.com",
      "type": "external_account",
      "audience": "//iam.googleapis.com/projects/16065310909/locations/global/workloadIdentityPools/ibm-clusters/providers/ppc64le",
      "subject_token_type": "urn:ietf:params:oauth:token-type:jwt",
      "token_url": "https://sts.googleapis.com/v1/token",
      "credential_source": {
        "file": "/var/run/secrets/google-iam-token/serviceaccount/token",
        "format": {
          "type": "text"
        }
      }
    }
