apiVersion: v1
kind: Secret
metadata:
  name: service-account
  namespace: test-pods
stringData:
  service-account.json: |
    {
      "universe_domain": "googleapis.com",
      "type": "external_account",
      "audience": "//iam.googleapis.com/projects/16065310909/locations/global/workloadIdentityPools/ibm-clusters/providers/ppc64le",
      "subject_token_type": "urn:ietf:params:oauth:token-type:jwt",
      "token_url": "https://sts.googleapis.com/v1/token",
      "credential_source": {
        "file": "/var/run/secrets/google-iam-token/serviceaccount/token",
        "format": {
          "type": "text"
        }
      }
    }
