apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: service-account
  namespace: test-pods
spec:
  data:
    - remoteRef:
        key: prow-build-service-account
      secretKey: service-account.json
  secretStoreRef:
    kind: ClusterSecretStore
    name: k8s-infra-prow-build
