{
 "title": "Jobs",
 "tags": [ "prow" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(up{cluster!~\"gke-utility|mimir\"}, cluster)"
   },
   {
    "name": "org",
    "label": "Organisation",
    "query": "label_values(prow:job{cluster=~\"$cluster\"}, org)"
   },
   {
    "name": "repo",
    "label": "Repository",
    "query": "label_values(prow:job{cluster=~\"$cluster\",org=\"$org\"}, repo)"
   },
   {
    "name": "job",
    "query": "label_values(prow:job{cluster=~\"$cluster\",org=\"$org\",repo=\"$repo\"}, name)"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Jobs",
   "type": "table",
   "gridPos": { "h": 17, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (name) (prow:job{cluster=~\"$cluster\",org=\"$org\",repo=\"$repo\"})"
    }
   ]
  },
  {
   "title": "Pending Jobs",
   "type": "table",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "(time() - prow:job:pending_since_time{cluster=~\"$cluster\",org=~\"$org\", repo=~\"$repo\"})"
    }
   ]
  },
  {
   "title": "Running Jobs",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 4, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count by (name) (prow:job{cluster=~\"$cluster\",phase=\"Running\",org=\"$org\",repo=\"$repo\"})",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Memory Usage per Job",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 10, "x": 4, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (name) (prow:job:memory_working_set_bytes{cluster=~\"$cluster\",phase=\"Running\",org=\"$org\",repo=\"$repo\"})",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Pending Jobs",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count by (name) (prow:job:pending{cluster=~\"$cluster\",org=\"$org\",repo=\"$repo\"})",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Memory Requested",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (sum (prow:job:resource_requests_memory_bytes{cluster=~\"$cluster\",org=\"$org\",repo=\"$repo\"}) / sum (prow:node:memory_capacity_bytes{cluster=~\"$cluster\"}))",
     "legendFormat": "requests"
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 2, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (sum (prow:job:memory_working_set_bytes{cluster=~\"$cluster\",phase=\"Running\",org=\"$org\",repo=\"$repo\"}) / sum (prow:node:memory_capacity_bytes{cluster=~\"$cluster\"}))",
     "legendFormat": "used"
    }
   ]
  },
  {
   "title": "CPU Usage per Job",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 10, "x": 14, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (name) (prow:job:cpu_usage_seconds_rate:1m{cluster=~\"$cluster\",phase=\"Running\",org=\"$org\",repo=\"$repo\"})",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "CPU Requested",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "100 * (sum (prow:job:resource_requests_cpu_cores{cluster=~\"$cluster\",org=\"$org\",repo=\"$repo\"}) / sum (prow:node:cpu_capacity_cores{cluster=~\"$cluster\"}))",
     "legendFormat": "requests"
    }
   ]
  },
  {
   "title": "CPU Used",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 2, "y": 24 },
   "targets": [
    {
     "expr": "100 * (sum (prow:job:cpu_usage_seconds_rate:1m{cluster=~\"$cluster\",phase=\"Running\",org=\"$org\",repo=\"$repo\"}) / sum (prow:node:cpu_capacity_cores{cluster=~\"$cluster\"}))",
     "legendFormat": "used"
    }
   ]
  },
  {
   "title": "Resource Usage for $job",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "repeat": "job",
   "collapsed": true,
   "panels": [
    {
     "title": "Memory",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum (prow:job:memory_working_set_bytes{cluster=~\"$cluster\",phase=\"Running\",org=\"$org\",repo=\"$repo\",name=~\"$job\"})",
       "legendFormat": "used"
      },
      {
       "expr": "sum (prow:job:resource_requests_memory_bytes{cluster=~\"$cluster\",phase=\"Running\",org=\"$org\",repo=\"$repo\",name=~\"$job\"})",
       "legendFormat": "requested"
      },
      {
       "expr": "sum (prow:job:resource_limits_memory_bytes{cluster=~\"$cluster\",phase=\"Running\",org=\"$org\",repo=\"$repo\",name=~\"$job\"})",
       "legendFormat": "limit"
      }
     ]
    },
    {
     "title": "CPU",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 31 },
     "targets": [
      {
       "expr": "sum (prow:job:cpu_usage_seconds_rate:1m{cluster=~\"$cluster\",phase=\"Running\",org=\"$org\",repo=\"$repo\",name=~\"$job\"})",
       "legendFormat": "used"
      },
      {
       "expr": "sum (prow:job:resource_requests_cpu_cores{cluster=~\"$cluster\",phase=\"Running\",org=\"$org\",repo=\"$repo\",name=~\"$job\"})",
       "legendFormat": "requested"
      },
      {
       "expr": "sum (prow:job:resource_limits_cpu_cores{cluster=~\"$cluster\",phase=\"Running\",org=\"$org\",repo=\"$repo\",name=~\"$job\"})",
       "legendFormat": "limit"
      }
     ]
    }
   ]
  }
 ]
}