{
 "title": "Organisations",
 "tags": [ "prow" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(up{cluster!~\"gke-utility|mimir\"}, cluster)"
   },
   {
    "name": "org",
    "query": "label_values(prow:job{cluster=~\"$cluster\"}, org)"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Organisations",
   "type": "table",
   "gridPos": { "h": 17, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (org) (prow:job{cluster=~\"$cluster\",org!=\"\"})"
    }
   ]
  },
  {
   "title": "Pending Jobs",
   "type": "table",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "(time() - prow:job:pending_since_time{cluster=~\"$cluster\",org=~\"$org\"})"
    }
   ]
  },
  {
   "title": "Running Jobs",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 10, "x": 4, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count by (org) (prow:job{cluster=~\"$cluster\",phase=\"Running\",org!=\"\"})",
     "legendFormat": "{{ org }}"
    },
    {
     "expr": "count (prow:job:pending{cluster=~\"$cluster\",phase=\"Running\",org=\"\"})",
     "legendFormat": "(no org)"
    }
   ]
  },
  {
   "title": "Memory Usage per Organisation",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 10, "x": 4, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (org) (prow:job:memory_working_set_bytes{cluster=~\"$cluster\",phase=\"Running\"})",
     "legendFormat": "{{ org }}"
    }
   ]
  },
  {
   "title": "Pending Jobs",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 10, "x": 14, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count by (org) (prow:job:pending{cluster=~\"$cluster\",org!=\"\"})",
     "legendFormat": "{{ org }}"
    },
    {
     "expr": "count (prow:job:pending{cluster=~\"$cluster\",org=\"\"})",
     "legendFormat": "(no org)"
    }
   ]
  },
  {
   "title": "Memory Requested",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (sum (prow:job:resource_requests_memory_bytes{cluster=~\"$cluster\"}) / sum (prow:node:memory_capacity_bytes{cluster=~\"$cluster\"}))",
     "legendFormat": "requests"
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 2, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (sum (prow:job:memory_working_set_bytes{cluster=~\"$cluster\",phase=\"Running\"}) / sum (prow:node:memory_capacity_bytes{cluster=~\"$cluster\"}))",
     "legendFormat": "used"
    }
   ]
  },
  {
   "title": "CPU Usage per Organisation",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 10, "x": 14, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (org) (prow:job:cpu_usage_seconds_rate:1m{cluster=~\"$cluster\",phase=\"Running\"})",
     "legendFormat": "{{ org }}"
    }
   ]
  },
  {
   "title": "CPU Requested",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (sum (prow:job:resource_requests_cpu_cores{cluster=~\"$cluster\"}) / sum (prow:node:cpu_capacity_cores{cluster=~\"$cluster\"}))",
     "legendFormat": "requests"
    }
   ]
  },
  {
   "title": "CPU Used",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 2, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (sum (prow:job:cpu_usage_seconds_rate:1m{cluster=~\"$cluster\",phase=\"Running\"}) / sum (prow:node:cpu_capacity_cores{cluster=~\"$cluster\"}))",
     "legendFormat": "used"
    }
   ]
  },
  {
   "title": "Resource Usage not attributed to any organisation",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum (prow:job:memory_working_set_bytes{cluster=~\"$cluster\",phase=\"Running\",org=\"\"})",
       "legendFormat": "used"
      },
      {
       "expr": "sum (prow:job:resource_requests_memory_bytes{cluster=~\"$cluster\",phase=\"Running\",org=\"\"})",
       "legendFormat": "requested"
      },
      {
       "expr": "sum (prow:job:resource_limits_memory_bytes{cluster=~\"$cluster\",phase=\"Running\",org=\"\"})",
       "legendFormat": "limit"
      }
     ]
    },
    {
     "title": "CPU",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
     "targets": [
      {
       "expr": "sum (prow:job:cpu_usage_seconds_rate:1m{cluster=~\"$cluster\",phase=\"Running\",org=\"\"})",
       "legendFormat": "used"
      },
      {
       "expr": "sum (prow:job:resource_requests_cpu_cores{cluster=~\"$cluster\",phase=\"Running\",org=\"\"})",
       "legendFormat": "requested"
      },
      {
       "expr": "sum (prow:job:resource_limits_cpu_cores{cluster=~\"$cluster\",phase=\"Running\",org=\"\"})",
       "legendFormat": "limit"
      }
     ]
    }
   ]
  },
  {
   "title": "Resource Usage for $org",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "repeat": "org",
   "collapsed": true,
   "panels": [
    {
     "title": "Memory",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum (prow:job:memory_working_set_bytes{cluster=~\"$cluster\",phase=\"Running\",org=~\"$org\"})",
       "legendFormat": "used"
      },
      {
       "expr": "sum (prow:job:resource_requests_memory_bytes{cluster=~\"$cluster\",phase=\"Running\",org=~\"$org\"})",
       "legendFormat": "requested"
      },
      {
       "expr": "sum (prow:job:resource_limits_memory_bytes{cluster=~\"$cluster\",phase=\"Running\",org=~\"$org\"})",
       "legendFormat": "limit"
      }
     ]
    },
    {
     "title": "CPU",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 21 },
     "targets": [
      {
       "expr": "sum (prow:job:cpu_usage_seconds_rate:1m{cluster=~\"$cluster\",phase=\"Running\",org=~\"$org\"})",
       "legendFormat": "used"
      },
      {
       "expr": "sum (prow:job:resource_requests_cpu_cores{cluster=~\"$cluster\",phase=\"Running\",org=~\"$org\"})",
       "legendFormat": "requested"
      },
      {
       "expr": "sum (prow:job:resource_limits_cpu_cores{cluster=~\"$cluster\",phase=\"Running\",org=~\"$org\"})",
       "legendFormat": "limit"
      }
     ]
    }
   ]
  }
 ]
}