# google group for gcr.io/k8s-staging-nvidia-gpu is k8s-infra-staging-nvidia-gpu@kubernetes.io
registries:
- name: gcr.io/k8s-staging-nvidia-gpu
  src: true
- name: us.gcr.io/k8s-artifacts-prod/nvidia-gpu
  service-account: k8s-infra-gcr-promoter@k8s-artifacts-prod.iam.gserviceaccount.com
- name: eu.gcr.io/k8s-artifacts-prod/nvidia-gpu
  service-account: k8s-infra-gcr-promoter@k8s-artifacts-prod.iam.gserviceaccount.com
- name: asia.gcr.io/k8s-artifacts-prod/nvidia-gpu
  service-account: k8s-infra-gcr-promoter@k8s-artifacts-prod.iam.gserviceaccount.com