---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: powervs-csi-driver-api-key
  namespace: kube-system
spec:
  refreshInterval: 30m
  secretStoreRef:
    name: secretstore-ibm-k8s
    kind: ClusterSecretStore
  target:
    name: ibm-secret
    creationPolicy: Owner
  data:
    - secretKey: IBMCLOUD_API_KEY
      remoteRef:
        key: iam_credentials/b6edf285-6dd7-1957-34e1-cfae2cb3e56f
