{
 "title": "Organisations",
 "tags": [ "prow" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   { "name": "org", "query": "label_values(prow:job, org)" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Organisations",
   "type": "table",
   "gridPos": { "h": 17, "w": 4, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by (org) (prow:job{org!=\"\"})"
    }
   ]
  },
  {
   "title": "Pending Jobs",
   "type": "table",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 1 },
   "targets": [
    {
     "expr": "(time() - prow:job:pending_since_time) > 60"
    }
   ]
  },
  {
   "title": "Running Jobs",
   "type": "graph",
   "gridPos": { "h": 9, "w": 10, "x": 4, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count by (org) (prow:job{phase=\"Running\",org!=\"\"})",
     "legendFormat": "{{ org }}"
    },
    {
     "expr": "count (prow:job:pending{phase=\"Running\",org=\"\"})",
     "legendFormat": "(no org)"
    }
   ]
  },
  {
   "title": "Pending Jobs",
   "type": "graph",
   "gridPos": { "h": 9, "w": 10, "x": 14, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count by (org) (prow:job:pending{org!=\"\"})",
     "legendFormat": "{{ org }}"
    },
    {
     "expr": "count (prow:job:pending{org=\"\"})",
     "legendFormat": "(no org)"
    }
   ]
  },
  {
   "title": "Memory Requested",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 18 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 * (sum (prow:job:resource_requests_memory_bytes) / sum (prow:node:memory_capacity_bytes))",
     "legendFormat": "requests"
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 2, "y": 18 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 * (sum (prow:job:memory_working_set_bytes{phase=\"Running\"}) / sum (prow:node:memory_capacity_bytes))",
     "legendFormat": "used"
    }
   ]
  },
  {
   "title": "Memory Usage per Organisation",
   "type": "graph",
   "gridPos": { "h": 10, "w": 10, "x": 4, "y": 18 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (org) (prow:job:memory_working_set_bytes{phase=\"Running\"})",
     "legendFormat": "{{ org }}"
    }
   ]
  },
  {
   "title": "CPU Usage per Organisation",
   "type": "graph",
   "gridPos": { "h": 10, "w": 10, "x": 14, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (org) (prow:job:cpu_usage_seconds_rate:1m{phase=\"Running\"})",
     "legendFormat": "{{ org }}"
    }
   ]
  },
  {
   "title": "CPU Requested",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 23 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 * (sum (prow:job:resource_requests_cpu_cores) / sum (prow:node: cpu_capacity_cores))",
     "legendFormat": "requests"
    }
   ]
  },
  {
   "title": "CPU Used",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 2, "y": 23 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 * (sum (prow:job:cpu_usage_seconds_rate:1m{phase=\"Running\"}) / sum (prow:node:cpu_capacity_cores))",
     "legendFormat": "used"
    }
   ]
  },
  {
   "title": "Resource Usage not attributed to any organisation",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum (prow:job:memory_working_set_bytes{phase=\"Running\",org=\"\"})",
       "legendFormat": "used"
      },
      {
       "expr": "sum (prow:job:resource_requests_memory_bytes{phase=\"Running\",org=\"\"})",
       "legendFormat": "requested"
      },
      {
       "expr": "sum (prow:job:resource_limits_memory_bytes{phase=\"Running\",org=\"\"})",
       "legendFormat": "limit"
      }
     ]
    },
    {
     "title": "CPU",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum (prow:job:cpu_usage_seconds_rate:1m{phase=\"Running\",org=\"\"})",
       "legendFormat": "used"
      },
      {
       "expr": "sum (prow:job:resource_requests_cpu_cores{phase=\"Running\",org=\"\"})",
       "legendFormat": "requested"
      },
      {
       "expr": "sum (prow:job:resource_limits_cpu_cores{phase=\"Running\",org=\"\"})",
       "legendFormat": "limit"
      }
     ]
    }
   ]
  },
  {
   "title": "Resource Usage for $org",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "repeat": "org",
   "collapsed": true,
   "panels": [
    {
     "title": "Memory",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum (prow:job:memory_working_set_bytes{phase=\"Running\",org=~\"$org\"})",
       "legendFormat": "used"
      },
      {
       "expr": "sum (prow:job:resource_requests_memory_bytes{phase=\"Running\",org=~\"$org\"})",
       "legendFormat": "requested"
      },
      {
       "expr": "sum (prow:job:resource_limits_memory_bytes{phase=\"Running\",org=~\"$org\"})",
       "legendFormat": "limit"
      }
     ]
    },
    {
     "title": "CPU",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 21 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum (prow:job:cpu_usage_seconds_rate:1m{phase=\"Running\",org=~\"$org\"})",
       "legendFormat": "used"
      },
      {
       "expr": "sum (prow:job:resource_requests_cpu_cores{phase=\"Running\",org=~\"$org\"})",
       "legendFormat": "requested"
      },
      {
       "expr": "sum (prow:job:resource_limits_cpu_cores{phase=\"Running\",org=~\"$org\"})",
       "legendFormat": "limit"
      }
     ]
    }
   ]
  }
 ]
}