apiVersion: v1
kind: ServiceAccount
metadata:
  name: prow-build
  namespace: test-pods
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::855606814420:role/node-e2e-tests
  name: node-e2e-tests
  namespace: test-pods
