initContainers:
- name: initialize-repos
  command:
  - /init-repo
  - --alsologtostderr
  - --config=/etc/munge-config/config
  - --rules-file=/etc/publisher-rules/config
  - 2>&1
  image: DOCKER_IMAGE
  imagePullPolicy: Always
  resources:
    requests:
      cpu: 300m
      memory: 200Mi
    limits:
      cpu: 2
      memory: 1.6Gi
  volumeMounts:
  - mountPath: /etc/munge-config
    name: munge-config
  - mountPath: /go-workspace
    name: publisher-gopath
  - mountPath: /etc/publisher-rules
    name: publisher-rules
  - mountPath: /.cache
    name: cache
containers:
- name: publisher
  command:
  - /publishing-bot
  - --alsologtostderr
  - --config=/etc/munge-config/config
  - --token-file=/etc/secret-volume/token
  - --interval=0
  - --server-port=8080
  - 2>&1
  image: DOCKER_IMAGE
  imagePullPolicy: Always
  livenessProbe:
    httpGet:
      path: /healthz
      port: 80
  resources:
    requests:
      cpu: 300m
      memory: MEMORY_REQUESTS
    limits:
      cpu: 2
      memory: MEMORY_LIMITS
  volumeMounts:
  - mountPath: /etc/munge-config
    name: munge-config
  - mountPath: /etc/publisher-rules
    name: publisher-rules
  - mountPath: /etc/secret-volume
    name: secret-volume
  - mountPath: /netrc
    name: netrc
  - mountPath: /gitrepos
    name: repo
  - mountPath: /go-workspace
    name: publisher-gopath
  - mountPath: /.cache
    name: cache
volumes:
- name: munge-config
  configMap:
    name: publisher-config
- name: publisher-rules
  configMap:
    name: publisher-rules
- name: secret-volume
  secret:
    secretName: github-token
- name: repo
  emptyDir: {}
- name: cache
  emptyDir: {}
- name: netrc
  emptyDir:
    medium: Memory
- name: publisher-gopath
  persistentVolumeClaim:
    claimName: publisher-gopath
