kind: Service
apiVersion: v1
metadata:
  name: health
  namespace: publishing-bot
spec:
  selector:
    name: publisher
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
