apiVersion: apps/v1
kind: Deployment
metadata:
  name: boskos-janitor
  labels:
    app: boskos-janitor
  namespace: test-pods
spec:
  replicas: 2 # 2 distributed janitor instances
  selector:
    matchLabels:
      app: boskos-janitor
  template:
    metadata:
      labels:
        app: boskos-janitor
    spec:
      terminationGracePeriodSeconds: 300
      serviceAccountName: boskos-janitor
      containers:
      - name: boskos-janitor
        image: gcr.io/k8s-staging-boskos/janitor:v20200819-984516e
        args:
        - --boskos-url=http://boskos.test-pods.svc.cluster.local.
        - --resource-type=gce-project,gpu-project,scalability-project
        - --pool-size=20
        - --
        - --hours=0
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    iam.gke.io/gcp-service-account: boskos-janitor@k8s-infra-prow-build.iam.gserviceaccount.com
  name: boskos-janitor
  namespace: test-pods
