apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: slack-infra
  annotations:
    kubernetes.io/ingress.global-static-ip-name: slack-infra-ingress-prod
    kubernetes.io/ingress.class: gce
    networking.gke.io/managed-certificates: slack-infra
spec:
  backend:
    serviceName: slackin2
    servicePort: 80
  rules:
    - http:
        paths:
          - path: /infra/event-log/*
            backend:
              serviceName: slack-event-log
              servicePort: 80
          - path: /infra/moderator/*
            backend:
              serviceName: slack-moderator
              servicePort: 80
          - path: /infra/welcomer/*
            backend:
              serviceName: slack-welcomer
              servicePort: 80
          - path: /infra/post-message/*
            backend:
              serviceName: slack-post-message
              servicePort: 80
          - path: /infra/moderator-words/*
            backend:
              serviceName: slack-moderator-words
              servicePort: 80
