apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: elekto-secret # The name of the Kubernetes Secret
  namespace: elekto
  labels:
    app: elekto
spec:
  backendType: gcpSecretsManager
  projectId: kubernetes-public
  data:
    - key: elekto-db-database
      name: DB_DATABASE
      version: latest
    - key: elekto-db-host
      name: DB_HOST
      version: latest
    - key: elekto-db-password
      name: DB_PASSWORD
      version: latest
    - key: elekto-db-port
      name: DB_PORT
      version: latest
    - key: elekto-db-username
      name: DB_USERNAME
      version: latest
    - key: elekto-github-client-id # The name of the GSM secret
      name: GITHUB_CLIENT_ID # The key to write to in the Kubernetes Secret
      version: latest # The version of the GSM secret
    - key: elekto-github-client-secret
      name: GITHUB_CLIENT_SECRET
      version: latest
    - key: elekto-meta-secret
      name: META_SECRET
      version: latest
    - key: elekto-app-key
      name: APP_KEY
      version: latest
