{
 "title": "Builds (AWS)",
 "tags": [ "prow" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(prow:job, cluster)"
   },
   {
    "name": "org",
    "label": "Organisation",
    "query": "label_values(prow:job{cluster=~\"$cluster\"}, org)"
   },
   {
    "name": "repo",
    "label": "Repository",
    "query": "label_values(prow:job{cluster=~\"$cluster\",org=\"$org\"}, repo)"
   },
   {
    "name": "job",
    "query": "label_values(prow:job{cluster=~\"$cluster\",org=\"$org\",repo=\"$repo\"}, name)"
   },
   {
    "name": "build",
    "query": "label_values(prow:job{cluster=~\"$cluster\",org=\"$org\",repo=\"$repo\",name=\"$job\"}, id)"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Running / Pending Builds",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count (prow:job{cluster=~\"$cluster\",phase=\"Running\",org=\"$org\",repo=\"$repo\",name=\"$job\"})",
     "legendFormat": "running"
    },
    {
     "expr": "count (prow:job:pending{cluster=~\"$cluster\",org=\"$org\",repo=\"$repo\",name=\"$job\"})",
     "legendFormat": "pending"
    }
   ]
  },
  {
   "title": "Pending Builds",
   "type": "table",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "(time() - prow:job:pending_since_time{cluster=~\"$cluster\",org=\"$org\",repo=\"$repo\",name=\"$job\"})"
    }
   ]
  },
  {
   "title": "Memory Requested",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (sum (prow:job:resource_requests_memory_bytes{cluster=~\"$cluster\",org=\"$org\",repo=\"$repo\",name=\"$job\"}) / sum (prow:node:memory_capacity_bytes{cluster=~\"$cluster\"}))",
     "legendFormat": "requests"
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 2, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (sum (prow:job:memory_working_set_bytes{cluster=~\"$cluster\",phase=\"Running\",org=\"$org\",repo=\"$repo\",name=\"$job\"}) / sum (prow:node:memory_capacity_bytes{cluster=~\"$cluster\"}))",
     "legendFormat": "used"
    }
   ]
  },
  {
   "title": "Memory Usage per Build",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 10, "x": 4, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (id) (prow:job:memory_working_set_bytes{cluster=~\"$cluster\",phase=\"Running\",org=\"$org\",repo=\"$repo\",name=\"$job\"})",
     "legendFormat": "{{ id }}"
    }
   ]
  },
  {
   "title": "CPU Usage per Build",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 10, "x": 14, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (id) (prow:job:cpu_usage_seconds_rate:1m{cluster=~\"$cluster\",phase=\"Running\",org=\"$org\",repo=\"$repo\",name=\"$job\"})",
     "legendFormat": "{{ id }}"
    }
   ]
  },
  {
   "title": "CPU Requested",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (sum (prow:job:resource_requests_cpu_cores{cluster=~\"$cluster\",org=\"$org\",repo=\"$repo\",name=\"$job\"}) / sum (prow:node:cpu_capacity_cores{cluster=~\"$cluster\"}))",
     "legendFormat": "requests"
    }
   ]
  },
  {
   "title": "CPU Used",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 2, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (sum (prow:job:cpu_usage_seconds_rate:1m{cluster=~\"$cluster\",phase=\"Running\",org=\"$org\",repo=\"$repo\",name=\"$job\"}) / sum (prow:node:cpu_capacity_cores{cluster=~\"$cluster\"}))",
     "legendFormat": "used"
    }
   ]
  },
  { "title": "Resource Usage for $build", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 }, "repeat": "build" },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum (prow:job:memory_working_set_bytes{cluster=~\"$cluster\",phase=\"Running\",org=\"$org\",repo=\"$repo\",name=\"$job\",id=~\"$build\"})",
     "legendFormat": "used"
    },
    {
     "expr": "sum (prow:job:resource_requests_memory_bytes{cluster=~\"$cluster\",phase=\"Running\",org=\"$org\",repo=\"$repo\",name=\"$job\",id=~\"$build\"})",
     "legendFormat": "requested"
    },
    {
     "expr": "sum (prow:job:resource_limits_memory_bytes{cluster=~\"$cluster\",phase=\"Running\",org=\"$org\",repo=\"$repo\",name=\"$job\",id=~\"$build\"})",
     "legendFormat": "limit"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum (prow:job:cpu_usage_seconds_rate:1m{cluster=~\"$cluster\",phase=\"Running\",org=\"$org\",repo=\"$repo\",name=\"$job\",id=~\"$build\"})",
     "legendFormat": "used"
    },
    {
     "expr": "sum (prow:job:resource_requests_cpu_cores{cluster=~\"$cluster\",phase=\"Running\",org=\"$org\",repo=\"$repo\",name=\"$job\",id=~\"$build\"})",
     "legendFormat": "requested"
    },
    {
     "expr": "sum (prow:job:resource_limits_cpu_cores{cluster=~\"$cluster\",phase=\"Running\",org=\"$org\",repo=\"$repo\",name=\"$job\",id=~\"$build\"})",
     "legendFormat": "limit"
    }
   ]
  }
 ]
}