apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-credentials
spec:
  dataFrom:
  - extract:
      key: grafana-credentials
  secretStoreRef:
    kind: ClusterSecretStore
    name: k8s-infra-prow-build
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mimir-credentials
spec:
  data:
    - secretKey: username
      remoteRef:
        key: mimir-credentials
        property: username
    - secretKey: password
      remoteRef:
        key: mimir-credentials
        property: password
  secretStoreRef:
    kind: ClusterSecretStore
    name: k8s-infra-prow-build
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: slack-k8s-infra-alerts-token
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: k8s-infra-prow-build
    kind: ClusterSecretStore
  target:
    name: slack-k8s-infra-alerts-token
    creationPolicy: Owner
  data:
  - secretKey: url
    remoteRef:
      key: slack-credentials
      property: k8s-infra-alerts
