apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: k8s-gcp-gcve-credentials
  namespace: test-pods
spec:
  data:
    - remoteRef:
        key: k8s-gcp-gcve-ci-password
      secretKey: password
    - remoteRef:
        key: k8s-gcp-gcve-ci-thumbprint
      secretKey: thumbprint
    - remoteRef:
        key: k8s-gcp-gcve-ci-username
      secretKey: username
    - remoteRef:
        key: k8s-gcp-gcve-ci-url
      secretKey: url
  secretStoreRef:
    kind: ClusterSecretStore
    name: broadcom-451918
