/*
Copyright 2022 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

/*
Geo-proximity, multi-region active-active delivery via CloudFront + Lambda@Edge.
Based on: https://aws.amazon.com/blogs/networking-and-content-delivery/using-amazon-cloudfront-and-amazon-s3-to-build-multi-region-active-active-geo-proximity-applications/

On a cache miss, the origin-request Lambda@Edge function looks up the S3
bucket replica closest to the executing edge region and rewrites the origin
request to it.
*/

locals {
  # Region -> regional S3 bucket domain, generated from the replicated buckets.
  region_bucket_domains = merge(
    { for region, mod in module.s3_buckets : region => mod.bucket_regional_domain_name },
    { "us-east-2" = module.us-east-2.bucket_regional_domain_name }
  )

  # The authoritative bucket, used when an edge region has no mapping.
  default_bucket_domain = module.us-east-2.bucket_regional_domain_name
  default_bucket_region = "us-east-2"
}

# --- Lambda@Edge origin router -----------------------------------------------

module "geo_router_role" {
  source          = "terraform-aws-modules/iam/aws//modules/iam-role"
  version         = "~> 6.6"
  name            = "${var.prefix}geo-router"
  use_name_prefix = false
  trust_policy_permissions = {
    LambdaEdgeAssume = {
      actions = ["sts:AssumeRole"]
      principals = [{
        type = "Service"
        identifiers = [
          "lambda.amazonaws.com",
          "edgelambda.amazonaws.com",
        ]
      }]
    }
  }
  policies = {
    AWSLambdaBasicExecutionRole = "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
  }
}

data "archive_file" "geo_router" {
  type        = "zip"
  output_path = "${path.module}/.terraform/tmp/geo-router.zip"

  source {
    filename = "index.py"
    content  = <<-PYTHON
      # Generated by Terraform - do not edit by hand.
      # Routes CloudFront origin requests to the closest S3 bucket replica.
      REGIONS_MAPPING = ${jsonencode(local.region_bucket_domains)}
      DEFAULT_BUCKET = "${local.default_bucket_domain}"
      DEFAULT_REGION = "${local.default_bucket_region}"


      def lambda_handler(event, context):
          request = event['Records'][0]['cf']['request']

          # Identify the edge region executing this replica of the function.
          lambda_region = context.invoked_function_arn.split(':')[3]

          # Pick the closest bucket, falling back to the default bucket.
          if lambda_region in REGIONS_MAPPING:
              domain_name = REGIONS_MAPPING[lambda_region]
              bucket_region = lambda_region
          else:
              domain_name = DEFAULT_BUCKET
              bucket_region = DEFAULT_REGION

          # Update the origin request object.
          request['origin']['s3']['domainName'] = domain_name
          request['origin']['s3']['region'] = bucket_region
          request['headers']['host'] = [{'key': 'host', 'value': domain_name}]
          return request
    PYTHON
  }
}

resource "aws_lambda_function" "geo_router" {
  region           = "us-east-1"
  function_name    = "${var.prefix}geo-router"
  role             = module.geo_router_role.arn
  runtime          = "python3.14"
  handler          = "index.lambda_handler"
  filename         = data.archive_file.geo_router.output_path
  source_code_hash = data.archive_file.geo_router.output_base64sha256
  publish          = true

  # Origin-request functions are limited to 30s / 10240 MB, keep defaults modest
  timeout     = 5
  memory_size = 128
}

module "acm" {
  source  = "terraform-aws-modules/acm/aws"
  version = "~> 6.3"
  region  = "us-east-1"

  domain_name            = "cdn.registry.k8s.io"
  validation_method      = "DNS"
  create_route53_records = false
}

# --- CloudFront distribution --------------------------------------------------

# Destination for CloudFront standard access logs (logging v2).
# CloudFront standard logging API calls must target us-east-1, so the log
# group has to live there too.
resource "aws_cloudwatch_log_group" "cdn" {
  region            = "us-east-1"
  name              = "/aws/cloudfront/${var.prefix}cdn"
  retention_in_days = 30
}

# Viewer-request routing:
#   /                                          -> 301 to the project repository
#   /containers/images/sha256:<64 hex digits>  -> forwarded to the origin
#   anything else                              -> 404, without hitting S3
resource "aws_cloudfront_function" "redirect_root" {
  name    = "${var.prefix}redirect-root"
  runtime = "cloudfront-js-2.0"
  comment = "Redirect / to GitHub, allow blob paths, 404 everything else"
  publish = true
  code    = <<-JS
    var BLOB_PATH = /^\/containers\/images\/sha256:[a-f0-9]{64}$/;

    function handler(event) {
      var request = event.request;

      if (request.uri === '/') {
        return {
          statusCode: 301,
          statusDescription: 'Moved Permanently',
          headers: {
            location: { value: 'https://github.com/kubernetes/registry.k8s.io' }
          }
        };
      }

      // Some clients percent-encode the digest separator.
      if (BLOB_PATH.test(request.uri.replace(/%3[Aa]/, ':'))) {
        return request;
      }

      return {
        statusCode: 404,
        statusDescription: 'Not Found',
        headers: {
          'content-type': { value: 'text/plain' },
          'cache-control': { value: 'max-age=300' }
        },
        body: 'Not Found\n'
      };
    }
  JS
}

# Echo the `rid` correlation id supplied by the redirect service back to the
# client as X-Request-Id, so a client-visible response can be joined against
# the redirect service logs and the `cs-uri-query` CDN log field.
#
# The value is user-controlled, so it is validated against a strict charset and
# length before being reflected into a response header.
resource "aws_cloudfront_function" "request_id" {
  name    = "${var.prefix}request-id"
  runtime = "cloudfront-js-2.0"
  comment = "Echo the rid query parameter back as X-Request-Id"
  publish = true
  code    = <<-JS
    function handler(event) {
      var response = event.response;
      var rid = event.request.querystring.rid;

      // CloudFront Functions require header names to be lowercase.
      if (rid && rid.value && /^[A-Za-z0-9._-]{1,64}$/.test(rid.value)) {
        response.headers['x-request-id'] = { value: rid.value };
      }

      return response;
    }
  JS
}

module "cdn" {
  source  = "terraform-aws-modules/cloudfront/aws"
  version = "~> 6.7"

  aliases = ["cdn.registry.k8s.io"]
  comment = "registry.k8s.io CDN"

  # Strip internal S3 metadata headers from CDN responses.
  response_headers_policies = {
    drop_s3_headers = {
      name    = "${var.prefix}drop-s3-headers"
      comment = "Strip internal S3 metadata headers from responses"
      remove_headers_config = {
        items = [
          { header = "x-amz-meta-mtime" },
          { header = "x-amz-meta-file-mtime" },
          { header = "x-amz-replication-status" },
          { header = "x-amz-server-side-encryption" },
          { header = "x-amz-version-id" },
        ]
      }
    }
  }

  # Blobs are content-addressed (sha256) and immutable: cache aggressively at
  # the edge to avoid per-request origin revalidation (RefreshHit).
  #
  # Query strings are deliberately excluded from the cache key so that the
  # correlation id appended to the redirect Location by the redirect service
  # does not fragment the cache. CloudFront still records the full query
  # string in the `cs-uri-query` access log field.
  cache_policies = {
    blobs = {
      name        = "${var.prefix}blobs"
      comment     = "Immutable, content-addressed blobs; query strings ignored"
      min_ttl     = 86400    # 1 day
      default_ttl = 2592000  # 30 days
      max_ttl     = 31536000 # 1 year
      parameters_in_cache_key_and_forwarded_to_origin = {
        enable_accept_encoding_brotli = true
        enable_accept_encoding_gzip   = true
        cookies_config = {
          cookie_behavior = "none"
        }
        headers_config = {
          header_behavior = "none"
        }
        query_strings_config = {
          query_string_behavior = "none"
        }
      }
    }
  }

  origin = {
    # S3 origin. On a cache miss the Lambda@Edge origin-request function
    # rewrites this origin to the bucket closest to the edge region.
    s3 = {
      domain_name = "prod-registry-k8s-io-us-east-2.s3.us-east-2.amazonaws.com"
    }
  }

  default_cache_behavior = {
    target_origin_id            = "s3"
    viewer_protocol_policy      = "redirect-to-https"
    cache_policy_key            = "blobs"
    response_headers_policy_key = "drop_s3_headers"

    allowed_methods = ["GET", "HEAD", "OPTIONS"]
    cached_methods  = ["GET", "HEAD"]
    compress        = true

    # Redirect / to the project repository before hitting cache or origin, and
    # echo the correlation id back to the client on the way out.
    function_association = {
      viewer-request = {
        function_arn = aws_cloudfront_function.redirect_root.arn
      }
      viewer-response = {
        function_arn = aws_cloudfront_function.request_id.arn
      }
    }

    # Geo-proximity routing: runs on cache miss, before the origin request.
    lambda_function_association = {
      origin-request = {
        lambda_arn   = aws_lambda_function.geo_router.qualified_arn
        include_body = false
      }
    }
  }
  # Ship standard access logs to CloudWatch Logs.
  enable_v2_logging = true
  v2_logging = {
    name                      = "${var.prefix}cdn-logs"
    delivery_destination_type = "CWL"
    delivery_destination_configuration = {
      destination_resource_arn = aws_cloudwatch_log_group.cdn.arn
    }

    # # Keep the field set narrow to limit CloudWatch ingestion cost.
    # # `cs-uri-query` carries the correlation id set by the redirect service.
    # record_fields = [
    #   "timestamp",
    #   "c-ip",
    #   "cs-method",
    #   "cs-uri-stem",
    #   "cs-uri-query",
    #   "sc-status",
    #   "sc-bytes",
    #   "time-to-first-byte",
    #   "x-edge-location",
    #   "x-edge-result-type",
    #   "x-edge-detailed-result-type",
    #   "x-edge-request-id",
    #   "cs-user-agent",
    # ]
  }
  viewer_certificate = {
    acm_certificate_arn = "arn:aws:acm:us-east-1:513428760722:certificate/05f38392-7830-4d6d-a3cb-bbf0f2bdce5f"
    ssl_support_method  = "sni-only"
  }
}

