apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: elekto-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: kubernetes-public
  data:
    - secretKey: DB_DATABASE
      remoteRef:
        key: elekto-db-database
    - secretKey: DB_HOST
      remoteRef:
        key: elekto-db-host
    - secretKey: DB_PASSWORD
      remoteRef:
        key: elekto-db-password
    - secretKey: DB_PORT
      remoteRef:
        key: elekto-db-port
    - secretKey: DB_USERNAME
      remoteRef:
        key: elekto-db-username
    - secretKey: GITHUB_CLIENT_ID
      remoteRef:
        key: elekto-github-client-id
    - secretKey: GITHUB_CLIENT_SECRET
      remoteRef:
        key: elekto-github-client-secret
    - secretKey: META_SECRET
      remoteRef:
        key: elekto-meta-secret
    - secretKey: APP_KEY
      remoteRef:
        key: elekto-app-key
