apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: kyverno
spec:
  goTemplate: true
  generators:
    - clusters:
        selector:
          matchLabels:
            cloud: ibm
    - clusters:
        selector:
          matchExpressions:
            - key: name
              operator: In
              values:
                - aks-prow-build
    - clusters:
        selector:
          matchLabels:
            cloud: eks
  template:
    metadata:
      name: "kyverno-{{ .name }}"
      annotations:
        argocd.argoproj.io/compare-options: ServerSideDiff=true,IncludeMutationWebhook=true
    spec:
      destination:
        namespace: kyverno
        server: "{{ .server }}"
      project: default
      sources:
        - chart: kyverno
          repoURL: "https://kyverno.github.io/kyverno"
          targetRevision: 3.8.1
          helm:
            releaseName: kyverno
            valueFiles:
              - $values/kubernetes/{{ .name }}/helm/kyverno.yaml
            valuesObject:
              config:
                resourceFiltersExclude:
                  - "[Binding,*,*]"
                  - "[Pod/binding,*,*]"
              features:
                logging:
                  format: json
              admissionController:
                rbac:
                  clusterRole:
                    extraResources:
                      - apiGroups:
                          - ""
                        resources:
                          - nodes
                        verbs:
                          - get
        - repoURL: "https://github.com/kubernetes/k8s.io.git"
          targetRevision: main
          ref: values
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
