apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: monitoring
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
spec:
  goTemplate: true
  generators:
    - clusters:
        selector:
          matchExpressions:
            - key: name
              operator: In
              values:
                - gke-prow-build
                - gke-utility
  template:
    metadata:
      name: 'monitoring-{{ .name }}'
    spec:
      destination:
        namespace: monitoring
        server: "{{ .server }}"
      project: default
      sources:
        - chart: kube-prometheus-stack
          repoURL: https://prometheus-community.github.io/helm-charts
          targetRevision:  85.1.3
          helm:
            releaseName: monitoring
            valueFiles:
              - $values/kubernetes/{{ .name }}/helm/monitoring.yaml
        - repoURL: https://github.com/kubernetes/k8s.io
          targetRevision: main
          ref: values
        - path: kubernetes/{{ .name }}/monitoring/
          repoURL: https://github.com/kubernetes/k8s.io
          targetRevision: main
      ignoreDifferences:
        - group: ""
          kind: Secret
          name: monitoring-grafana
          namespace: monitoring
          jsonPointers:
            - /data/admin-password
        - group: apps
          kind: Deployment
          name: monitoring-grafana
          namespace: monitoring
          jqPathExpressions:
            - '.spec.template.metadata.annotations["checksum/secret"]'
        - group: external-secrets.io
          kind: ExternalSecret
          name: mimir-credentials
          namespace: monitoring
          jsonPointers:
            - /metadata/finalizers
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - RespectIgnoreDifferences=true
          - ServerSideApply=true
        managedNamespaceMetadata:
          labels:
            istio-injection: enabled
