# Distribution
# Define the config

version: 0.1
log:
  accesslog:
    disabled: true
  level: debug
  fields:
    service: registry
    environment: development
auth:
  htpasswd:
    realm: basic-realm
    path: /etc/docker/registry/htpasswd
storage:
  delete:
    enabled: true
  filesystem:
    rootdirectory: /var/lib/registry
  maintenance:
    uploadpurging:
      enabled: false
http:
  addr: :5000
  secret: registry-k8s-io-registry-k8s-io
  host: https://bobymcbobs.pair.sharing.io:5000
  debug:
    addr: :5001
    prometheus:
      enabled: true
      path: /metrics
    headers:
      X-Content-Type-Options: [nosniff]
health:
  storagedriver:
    enabled: true
    interval: 10s
    threshold: 3
proxy:
  remoteurl: https://k8s.gcr.io
