kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: default
  labels:
    app: ghproxy
  name: ghproxy
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: standard
