apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: grafana
spec:
  hostnames:
    - monitoring.prow.k8s.io
  parentRefs:
    - name: istio-ingressgateway
      namespace: istio-system
      sectionName: https
  rules:
    - backendRefs:
        - name: monitoring-grafana
          port: 80
