apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mimir-credentials
spec:
  refreshInterval: 1h0m0s
  data:
    - secretKey: username
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: mimir-credentials
        metadataPolicy: None
        nullBytePolicy: Ignore
        property: username
    - secretKey: password
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: mimir-credentials
        metadataPolicy: None
        nullBytePolicy: Ignore
        property: password
  secretStoreRef:
    kind: ClusterSecretStore
    name: k8s-infra-prow
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
