apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mimir-credentials
spec:
  data:
    - secretKey: username
      remoteRef:
        key: mimir-credentials
        property: username
    - secretKey: password
      remoteRef:
        key: mimir-credentials
        property: password
  secretStoreRef:
    kind: ClusterSecretStore
    name: k8s-infra-prow
