# google group for gcr.io/k8s-staging-jobset is k8s-infra-staging-jobset@kubernetes.io
registries:
- name: gcr.io/k8s-staging-jobset
  src: true
- name: us.gcr.io/k8s-artifacts-prod/jobset
  service-account: k8s-infra-gcr-promoter@k8s-artifacts-prod.iam.gserviceaccount.com
- name: eu.gcr.io/k8s-artifacts-prod/jobset
  service-account: k8s-infra-gcr-promoter@k8s-artifacts-prod.iam.gserviceaccount.com
- name: asia.gcr.io/k8s-artifacts-prod/jobset
  service-account: k8s-infra-gcr-promoter@k8s-artifacts-prod.iam.gserviceaccount.com
imagesPath: "../../images/k8s-staging-jobset/images.yaml"