serviceAccount:
  create: true
  name: mimir

minio:
  enabled: false

kafka:
  enabled: false

gateway:
  enabled: true
  replicas: 2
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      memory: 512Mi
  nginx:
    basicAuth:
      enabled: true
      existingSecret: mimir-credentials

mimir:
  structuredConfig:
    limits:
      max_global_series_per_user: 1000000
      max_label_names_per_series: 50
      ingestion_rate: 100000
      ingestion_burst_size: 2000000
    ingest_storage:
      enabled: false
      kafka:
        address: null
        topic: null
        auto_create_topic_default_partitions: null
    distributor:
      remote_timeout: null
    ingester:
      push_grpc_method_enabled: true
    common:
      storage:
        backend: gcs
        gcs:
          bucket_name: k8s-infra-prow-mimir
    blocks_storage:
      backend: gcs
      storage_prefix: blocks
    ruler_storage:
      backend: gcs
      storage_prefix: ruler
    alertmanager_storage:
      backend: gcs
      storage_prefix: alertmanager

metaMonitoring:
  serviceMonitor:
    enabled: true

rollout_operator:
  enabled: true

alertmanager:
  persistentVolume:
    enabled: true
    storageClass: hyperdisk-balanced
    size: 50Gi
  replicas: 2
  resources:
    limits:
      memory: 1.4Gi
    requests:
      cpu: 1
      memory: 1Gi
  statefulSet:
    enabled: true

compactor:
  persistentVolume:
    size: 50Gi
    storageClass: hyperdisk-balanced
  resources:
    limits:
      memory: 2.1Gi
    requests:
      cpu: 1
      memory: 1.5Gi

distributor:
  replicas: 2
  resources:
    limits:
      memory: 5.7Gi
    requests:
      cpu: 1
      memory: 2Gi

ingester:
  zoneAwareReplication:
    enabled: false
  persistentVolume:
    size: 50Gi
    storageClass: hyperdisk-balanced
  replicas: 3
  resources:
    limits:
      memory: 8Gi
    requests:
      cpu: 1
      memory: 4Gi
  topologySpreadConstraints: {}

chunks-cache:
  enabled: true
  replicas: 2
  allocatedMemory: 2048

index-cache:
  enabled: true
  replicas: 1
  allocatedMemory: 1024

metadata-cache:
  enabled: true
  replicas: 1

results-cache:
  enabled: true
  replicas: 1

overrides_exporter:
  replicas: 1
  resources:
    limits:
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi

querier:
  replicas: 1
  resources:
    limits:
      memory: 5.6Gi
    requests:
      cpu: 1
      memory: 4Gi

query_frontend:
  replicas: 1
  resources:
    limits:
      memory: 2.8Gi
    requests:
      cpu: 1
      memory: 2Gi

ruler:
  replicas: 1
  resources:
    limits:
      memory: 2.8Gi
    requests:
      cpu: 1
      memory: 2Gi

store_gateway:
  zoneAwareReplication:
    enabled: false
  persistentVolume:
    size: 50Gi
    storageClass: hyperdisk-balanced
  replicas: 3
  resources:
    limits:
      memory: 2.1Gi
    requests:
      cpu: 1
      memory: 1.5Gi
  topologySpreadConstraints: {}
