apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  url: https://argo.k8s.io
  application.instanceLabelKey: infra.k8s.io/instance
  resource.compareoptions: |
    ignoreAggregatedRoles: true
  resource.customizations: |
    admissionregistration.k8s.io/MutatingWebhookConfiguration:
      ignoreDifferences: |
        jqPathExpressions:
        - '.webhooks[]?.clientConfig.caBundle'
        # Ignore AKS injections.
        - '.webhooks[]?.namespaceSelector.matchExpressions[] | select(.key == "control-plane")'
        - '.webhooks[]?.namespaceSelector.matchExpressions[] | select(.key == "kubernetes.azure.com/managedby")'
    admissionregistration.k8s.io/ValidatingWebhookConfiguration:
      ignoreDifferences: |
        jqPathExpressions:
        # Ignore AKS injections.
        - '.webhooks[]?.namespaceSelector.matchExpressions[] | select(.key == "control-plane")'
        - '.webhooks[]?.namespaceSelector.matchExpressions[] | select(.key == "kubernetes.azure.com/managedby")'
  kustomize.buildOptions: --load-restrictor LoadRestrictionsNone --enable-alpha-plugins
  statusbadge.enabled: "true"
  dex.config: |
    connectors:
      - type: authproxy
        id: oauth2-proxy
        name: OAuth2 Proxy
        config:
          userHeader: X-Auth-Request-Email
          groupHeader: X-Auth-Request-Groups
          userIDHeader: X-Auth-Request-User
